### ISSUE TITLE
--work-dir flag does not allow absolute/relative paths

### ISSUE THREAD

**Issue by wasimmer** [grow/grow#1005]
I am in the process of setting up build sharding, which looks like it will massively speed up build times for our project - thanks for that addition to Grow.

For a number of reasons, we don't build our project into the project directory, but instead to a directory under /tmp/. We do so by specifying an absolute path to the `--out-dir` flag when invoking `grow build`, i.e.

```
    grow build  \
        --no-preprocess  \
        --deployment="$environment"  \
        --shards=10  \
        --shard=$i  \
        --routes-file=routes.json  \
        --out-dir=/tmp/<xyz>/  \
        $PROJECT_DIR 
```

This works as expected (the project is built into /tmp/) - however, it appears as if paths outside of the project directory cannot be provided to `--work-dir` when invoking `grow deploy`: 

When providing the same, absolute path (i.e. `/tmp/<xyz>/`) to `--work-dir` it seems as if the path is appended to the path of the pod:

```
  grow deploy $environment  \
      --no-preprocess  \
      --routes-file=grow_deployment_control/routes.json  \
      --work-dir=/tmp/<xyz>/out-dir/  \
      $PROJECT_DIR
```

```
Error loading /<directory>/<filename>/
[Errno 2] No such file or directory: u'/<pod directory>/tmp/<xyz>/<directory>/<filename>/'
  File "/<>/.local/lib/python2.7/site-packages/grow/rendering/render_controller.py", line 168, in load
    rendered_content = self.pod.read_file(rendered_path)
  File "/<>/.local/lib/python2.7/site-packages/grow/pods/pods.py", line 840, in read_file
    return self.storage.read(path)
  File "/<>/.local/lib/python2.7/site-packages/grow/storage/file_storage.py", line 20, in read
    fp = open(filename)
```

When providing a relative path (i.e `.../../../tmp/<xyz>/`) to `--work-dir` an error is raised:

```
  grow deploy $environment  \
      --no-preprocess  \
      --routes-file=grow_deployment_control/routes.json  \
      --work-dir=.../../../tmp/<xyz>/  \
      $PROJECT_DIR
```

```
Error loading /<directory>/<filename>/
.. not allowed in file paths.
  File "/<>/.local/lib/python2.7/site-packages/grow/rendering/render_controller.py", line 168, in load
    rendered_content = self.pod.read_file(rendered_path)
  File "/<>/.local/lib/python2.7/site-packages/grow/pods/pods.py", line 838, in read_file
    path = self._normalize_path(pod_path)
  File "/<>/.local/lib/python2.7/site-packages/grow/pods/pods.py", line 184, in _normalize_path
    raise ValueError('.. not allowed in file paths.')
```

IMHO, absolute paths should be supported.

**Comment by Zoramite** [comment]
Thanks for filing this issue. And great to hear that you are working on using the work-dir. When I made it I specifically didn't allow the work dir to be outside of the pod for security reasons.

I will probably add a feature flag for grow that will allow you to specify that you want grow to be able to use external directories.

**Comment by Zoramite** [comment]
Thinking about it more a flag like I was thinking wouldn't give it much more security unless we did it outside of the podspec, which the current version of grow doesn't support.

**Comment by wasimmer** [comment]
That was a quick fix! Many thanks!
