### ISSUE TITLE
Text extraction and l10n overrides in JSON files

### ISSUE THREAD

**Issue by stevenle** [grow/grow#1027]
JSON parsing is significantly faster than YAML, but sometimes we need to use YAML for data content since it supports the `key@: value` text extraction and `key@locale: localized_value` l10n overrides.

Any chance we could support something similar with a custom JSON parser that traverses the keys? I don't think this'll have any issues with existing JSON files.

**Comment by Zoramite** [comment]
Once the data is parsed we use the `untag` to work through all the tagged keys. It should work just as well for json as yaml. The biggest part is just figuring out where we want to do the extra processing... We could do an `untag` jinja filter that would untag the data in templates or we could add it into the yaml constructors like we do for `!g.yaml`.

**Comment by stevenle** [comment]
I think the two most common ways to load json are `!g.json` within a content doc or `{{g.json()}}` within a template. I think it'd make sense to add `untag` within those loaders/constructors, or using an `|untag` filter is fine by me since it'd work with `g.csv` and any other data types we'd have in the future. Up to you with what makes the most sense from a maintainability perspective.
