### ISSUE TITLE
Macros as extensions

### ISSUE THREAD

**Issue by jeremydw** [grow/grow#1035]
We need to make a decision on how to approach macros as extensions.

Should we:

1. Fully support macros as extensions, allow you to add a macro to `extensions.txt` and `grow install` it, then configure it in `podspec.yaml`
1. Just provide a starter repository with common macros, and ask users to vendor the macros into their projects.

**Comment by Zoramite** [comment]
Overall, I am thinking of two ways we could do this:

1) Programatically. As part of the extension 'startup' it manually adds the macros using an API call in grow.
2) Conventionally. Macros are in a `macro` or similar directory in the extension and during startup they are automatically found and added to the global macros.

I think that the convention based would be easier for people to manage. As long as they don't need anything that would be useful from being able to programatically add them (such as config?)

**Comment by jeremydw** [comment]
I think #2 is the right approach for solving https://github.com/grow/grow/issues/1034 (i.e. place a template function in `/views/macros` and have it work in a global `macros` object)

We can delay implementing an official "installable" macro until after we're happy with how the solution for #1034 goes.
