### ISSUE TITLE
Can't get started with codelab theme or any other theme

### ISSUE THREAD

**Issue by Juankz** [grow/grow#1039]
Hello :)

I'm following the codelab of starting with grow: https://grow.io/codelab/3/
I run the commands in order
```
grow init codelab ./my-codelab/
cd my-codelab/
grow install
grow run
```

After the server is running I get this screen: 
![Screenshot_2019-11-29 Error 1](https://user-images.githubusercontent.com/18577412/69882667-f1422c80-129e-11ea-8849-0123da9d27a5.png)

Clicking traceback prints `false`. Tried other themes, all have similar problems. Tried `grow preprocess`, same result. 

**Testing environment:**
* OSX Mohave
* grow v.0.8.16

**Comment by jeremydw** [comment]
Hi Juan, do you see any other information in the output? Grow is looking for a generated CSS file; that would have been created by a Gulp task that Grow instruments when `grow run` starts. Mind trying to restart the server, or running `gulp build` and seeing if it generates the file in the `/dist/` folder?

The codelab and themes assume that you have a working Node environment on your machine (this page shows a few ways to get that working: https://grow.io/workflow/development-server/#mac-setup)

**Comment by Juankz** [comment]
Hey thanks for answering, here is the output from console:
```
$ grow run
Warning: libyaml missing, using slower yaml parser.
[16:52:12] 28 routes built in 0.004 s
               Pod: /Users/jvelandia/Experimentos/codelab
           Address: http://localhost:8080/
      Server ready. Press ctrl-c to quit.
500: / - Either no file exists at "/dist/main.min.css" or the "static_dirs" setting was not configured for this path in podspec.yaml.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/grow/server/main.py", line 28, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/grow/server/main.py", line 70, in wsgi_app
    response = self.dispatch_request(request)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/grow/server/main.py", line 66, in dispatch_request
    return handlers.serve_pod(self.pod, request, matched)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/grow/server/handlers.py", line 108, in serve_pod
    rendered_document = controller.render(jinja_env=jinja_env, request=request)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/grow/rendering/render_controller.py", line 246, in render
    raise exception
BuildError: Either no file exists at "/dist/main.min.css" or the "static_dirs" setting was not configured for this path in podspec.yaml.
```
I have a working node environment (node v12.13.0)

Gulp build doesn't work, there is no `gulpfile.js` in the theme https://github.com/growthemes/codelab

Whatever task grow should run to compile `/dist/main.min.css` is simply not executing :/

**Comment by Juankz** [comment]
Update: Tried to use grow in linux but I get the same problem

**Comment by Zoramite** [comment]
This is happening because we removed our sass preprocessor in an earlier version of grow, but we never updated the codelab with that change. I'll work on updating the codelab code to use a preprocessor for compiling the sass.

**Comment by Zoramite** [comment]
I've updated the codelab to use the gulp preprocessor to generate the sass instead of using the older built-in preprocessor.

I had to temporarily disable the error page generation since it was causing issues with grow. I'll try and get that back sometime soon, but it should build and run correctly now if you redo the codelab.
