### ISSUE TITLE
A site scaffolder as an alternative to theming

### ISSUE THREAD

**Issue by uxder** [grow/grow#104]
I know there are themes for grow but I'm wondering if a site scaffolder has been considered for grow.  

I'm thinking of something similar to how http://yeoman.io/ scaffolds sites and it could be a simple as creating a yoemen grow generator (although it would then introduce a node and npm dependency).  The generator could include the default setup for any grow site and provide optional configurations.

I think this would allow fine-grain control when setting up a new grow site and additionally, serve as one centralised example of a boilerplate grow site.

Example of what it might be like:

$ grow scaffold
$ use gulp? [y/n]:
$ use sass? [y/n]:
$ use bootstrap? [y/n]
$ use angular? [y/n]
$ add example sample content? [y/n]
$ add inline comments to sample content (recommended for newcomers to grow)? [y/n]
$ (does magic!)

**Comment by Zoramite** [comment]
Good news, we are actually working on a [yo generator](https://github.com/grow/generator-grow) for grow :)

Feel free to help make it better. Right now it is pretty bare bones, but we are working on improving it 👍
