### ISSUE TITLE
TypeError: coercing to Unicode: need string or buffer, int found while updating from 0.7.6 to 0.8.16

### ISSUE THREAD

**Issue by ViktorZharina** [grow/grow#1046]
Try to update from version: 0.7.6 to latest version: 0.8.16
Link to my project for reproducing: https://github.com/ViktorZharina/static-blog-based-on-grow.

Got 

^[[Cblog    | Traceback (most recent call last):
blog    |   File "/usr/bin/grow", line 76, in <module>
blog    |     group.grow()
blog    |   File "/usr/lib/python2.7/site-packages/click/core.py", line 764, in __call__
blog    |     return self.main(*args, **kwargs)
blog    |   File "/usr/lib/python2.7/site-packages/click/core.py", line 717, in main
blog    |     rv = self.invoke(ctx)
blog    |   File "/usr/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
blog    |     return _process_result(sub_ctx.command.invoke(sub_ctx))
blog    |   File "/usr/lib/python2.7/site-packages/click/core.py", line 956, in invoke
blog    |     return ctx.invoke(self.callback, **ctx.params)
blog    |   File "/usr/lib/python2.7/site-packages/click/core.py", line 555, in invoke
blog    |     return callback(*args, **kwargs)
blog    |   File "/usr/lib/python2.7/site-packages/grow/commands/subcommands/run.py", line 54, in run
blog    |     update_check=update_check)
blog    |   File "/usr/lib/python2.7/site-packages/grow/server/manager.py", line 78, in start
blog    |     serving.run_simple(host, port, app, request_handler=handler, threaded=True)
blog    |   File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 1009, in run_simple
blog    |     inner()
blog    |   File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 962, in inner
blog    |     fd=fd,
blog    |   File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 805, in make_server
blog    |     host, port, app, request_handler, passthrough_errors, ssl_context, fd=fd
blog    |   File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 698, in __init__
blog    |     HTTPServer.__init__(self, server_address, handler)
blog    |   File "/usr/lib/python2.7/SocketServer.py", line 418, in __init__
blog    |     self.server_activate()
blog    |   File "/usr/lib/python2.7/site-packages/grow/server/manager.py", line 29, in server_activate
blog    |     self.pod.router.add_all(concrete=False)
blog    |   File "/usr/lib/python2.7/site-packages/grow/routing/router.py", line 72, in add_all
blog    |     concrete=concrete, unchanged_pod_paths=unchanged_pod_paths)
blog    |   File "/usr/lib/python2.7/site-packages/grow/routing/router.py", line 109, in add_all_docs
blog    |     self.add_docs(docs, concrete=concrete)
blog    |   File "/usr/lib/python2.7/site-packages/grow/routing/router.py", line 250, in add_docs
blog    |     if not self.pod.path_filter.is_valid(doc.get_serving_path()):
blog    |   File "/usr/lib/python2.7/site-packages/grow/common/utils.py", line 163, in __call__
blog    |     value = self.func(*args, **kwargs)
blog    |   File "/usr/lib/python2.7/site-packages/grow/documents/document.py", line 515, in get_serving_path
blog    |     self, path_format, locale=self.locale)
blog    |   File "/usr/lib/python2.7/site-packages/grow/routing/path_format.py", line 63, in format_doc
blog    |     params.update(self.params_doc(path, doc))
blog    |   File "/usr/lib/python2.7/site-packages/grow/routing/path_format.py", line 149, in params_doc
blog    |     params['slug'] = doc.slug
blog    |   File "/usr/lib/python2.7/site-packages/grow/documents/document.py", line 415, in slug
blog    |     return slugify.slugify(self.title)
blog    |   File "/usr/lib/python2.7/site-packages/slugify/slugify.py", line 104, in slugify
blog    |     text = _unicode(text, 'utf-8', 'ignore')
blog    | TypeError: coercing to Unicode: need string or buffer, int found
blog exited with code 1

Seems that I have some trouble string in slug but I don't understand where is it (in what post) and why old version works fine. Could you help with it?
Any additional info in my repo. Thanks.

**Comment by Zoramite** [comment]
I had a chance to look into your site a bit. There are two things that are broken from updating:

1. The `/content/posts/ru/2015-06-25-15-34-37-184@ru.md` document has a number for the title, which doesn't seem to play nicely with the updated slugify library that we are using. You can either update the document to add a `$slug: something` to specify the slug you want to use so it doesn't go through the slugify library for that doc or you can add something besides just a number to the title.
2. The Sass preprocessor was removed from grow in favor of using external libraries to do the sass preprocessing. You can update your site like I did for the codelab in this commit: https://github.com/growthemes/codelab/commit/f3be2d76fa4c650935dbdab2282e66b37e857aa2

**Comment by Zoramite** [comment]
Also, if you want to keep the slug for the blog post you should be able to `$slug: 1848` and have it still use the 1848 for the slug. Using the `$slug` should bypass the code that was causing errors.

**Comment by ViktorZharina** [comment]
Thanks for the answer. Will try.
