### ISSUE TITLE
Following semantic versioning

### ISSUE THREAD

**Issue by fotinakis** [grow/grow#105]
Up until now Grow has mostly followed a "increment patch version and wait for 1.0.0" versioning and release strategy. But the design is starting to stabilize quite a bit and I think the community could benefit from a more defined version practice.

I've had a lot of success following the semver model: http://semver.org/ — it's pretty intuitive:

> Given a version number MAJOR.MINOR.PATCH, increment the:
> - MAJOR version when you make incompatible API changes,
> - MINOR version when you add functionality in a backwards-compatible manner, and
> - PATCH version when you make backwards-compatible bug fixes.
> 
> Additional labels for pre-release and build metadata are available as extensions to the
> MAJOR.MINOR.PATCH format.

And:

> **How should I deal with revisions in the 0.y.z initial development phase?**
> The simplest thing to do is start your initial development release at 0.1.0 and then increment the minor version for each subsequent release.
> 
> **How do I know when to release 1.0.0?**
> If your software is being used in production, it should probably already be 1.0.0. If you have a stable API on which users have come to depend, you should be 1.0.0. If you're worrying a lot about backwards compatibility, you should probably already be 1.0.0.

So in this world, Grow should probably release a v1.0.0, but it's not required—we could simple tag the next release as v0.1.0, patches after that as v0.1.1, v0.1.2, and when new features are added v0.2.0, v0.2.1, etc. until ready to declare a major version.

**Comment by jeremydw** [comment]
Thanks for this. Grow is fairly stable and used in production workflows regularly in multiple environments now. After #95 is fixed, #99 is designed and implemented, and #107 is researched and maybe implemented we'll do a proper 1.0.0 and use semantic versioning with microversions and patches going forward. :+1:

**Comment by jeremydw** [comment]
Other dev process suggestions to implement from a discussion with @streeter:

- No more long-running `develop` branch. Just use `master` and only merge working code into `master`.
- Add a `CONTRIBUTING.md` file to describe contribution workflow.
- Releases should be based on tags. They are now already, but we will drop the "`master` equals released" philosophy.

**Comment by fotinakis** [comment]
👍 100% agreed. You could maybe avoid the CONTRIBUTING.md and just put steps at the bottom of the readme like many GitHub projects, unless you wanted a more in-depth process.

**Comment by jeremydw** [comment]
Yep, something quick in the README is probably what we'll do since this
process doesn't really have any special requirements and therefore not much
need for a separate file. :)

**Comment by Zoramite** [comment]
We are doing semantic versioning now, so I am going to close this issue.
