### ISSUE TITLE
Add node-sass to Dockerfile

### ISSUE THREAD

**Issue by jeremydw** [grow/grow#1051]
We moved the sass preprocessor out of Grow, but it might be nice to have it in the base Docker image. This would greatly speed up composed builds that `grow install` in sources and have a `node-sass` dependency.

We already have a bunch of random other dependencies installed in the base Docker image so it would be nice to throw in an `npm install node-sass` to save projects' `grow install` times.

**Comment by stevenle** [comment]
we should re-evaluate this and compare load times - node-sass installation isn't too bad on node v12.

**Comment by Zoramite** [comment]
I think it will also change depending on which version of node-sass there is. The image would probably get built with the latest at the time, but it would then be outdated if there are any new release of node-sass until the next grow version.

**Comment by Zoramite** [comment]
I'm going to close this for now as the caching after the initial build should handle it and be specific for the grow project.
