### ISSUE TITLE
Packaged release doesn't work on Ubuntu

### ISSUE THREAD

**Issue by matthiasrohmer** [grow/grow#1057]
Running the binary/packaged release of Grow (latest version, 0.8.19) on Ubuntu (not latest but 16.04 as that's the release Travis uses) fails with the following error:

```
$ grow --version
Traceback (most recent call last):
  File "site-packages/PyInstaller/loader/rthooks/pyi_rth_certifi.py", line 11, in <module>
  File "/tmp/pip-install-8XI4gY/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 395, in load_module
  File "ssl.py", line 98, in <module>
  File "/tmp/pip-install-8XI4gY/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 684, in load_module
ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/_MEI0CVwLO/libcrypto.so.1.1)
[6946] Failed to execute script pyi_rth_certifi
```

Installing/upgrading potentially needed dependencies with

https://github.com/grow/grow/blob/8711f0eaac3c3dfd1dcc12257baaed9d4fe56ba0/Dockerfile.master#L21-L29

also doesn't help. Installing via `pip install grow` works fine but of course requires pip to be correctly set up.

**Comment by jeremydw** [comment]
@zoramite I know we pruned dependencies recently; does this ring any bells with respect to some deps that were removed? Something related to `pyi_rth_certifi`?

**Comment by matthiasrohmer** [comment]
@Zoramite, friendly ping 🙂 Did you already had a chance to look into this?

**Comment by Zoramite** [comment]
I think that this may be a case since you are using a different Ubuntu version than we used to build the image. We are using the docker `ubuntu:latest` tag to build it. And from looking around for that Error it seems to be an issue between two different versions of ubuntu.

I don't have a good way to fix that issue, so you may just be stuck using the pip install version of it for now.

**Comment by Zoramite** [comment]
Also, does Travis let you use docker images yet? because we have a docker image that we use for GCB and CircleCI that has everything installed and ready to use grow commands.

**Comment by jeremydw** [comment]
FYI: In Grow 1x (python 3 compatibility), we've moved away from using and recommending the packaged release.

Installation and migration notes are here, long story short we recommend using pipenv to manage and use grow: 
https://grow.dev/migration/1.0.0/
