### ISSUE TITLE
Is there a road map for grow?

### ISSUE THREAD

**Issue by amandeeepsingh** [grow/grow#1076]
I am thinking of using grow for my website. I just want to know what's on the roadmap for grow and how does the future community support looks like.

Thanks!

**Comment by Zoramite** [comment]
Hi @amandeeepsingh We don't have a roadmap currently. Right now we are working on finishing up the python 3 conversion and the issue list is what we use to track what we need to work on.

You can see the overall documentation on grow.io to see what you can do generally with Grow.

Are there specific features that you are interested in?
