### ISSUE TITLE
Add hreflang and other metadata support to autogenerated sitemap.xml

### ISSUE THREAD

**Issue by jeremydw** [grow/grow#1082]
We should:

- Add leading `<?xml>` line
- Add `lastmod`
- Group localized pages together into `<url>` tags

Example updated syntax:

```
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    <url>
        <loc>https://example.com/</loc>
        <lastmod>2019-12-14</lastmod>
        <xhtml:link rel="alternate" hreflang="x-default" href="https://example.com/"/>
        <xhtml:link rel="alternate" hreflang="da-dk" href="https://example.com/dk/"/>
    </url>
```

**Comment by Zoramite** [comment]
I think that we may have some issues with the lastmod time. The file mod time isn't a good representation of when the content was updated (ex: it may pull in data from a yaml file that is referenced). We may be able to use the deploy log... but not sure how accurate some of that would be.

**Comment by Zoramite** [comment]
Looking at the template: https://github.com/grow/grow/blob/master/grow/pods/templates/sitemap.xml

It looks like we already have the leading `<?xml>` line and lastmod. But we should probably update to have the alter languages in there too.

**Comment by jeremydw** [comment]
Great. Let's scope this to updating the default template to include the groupings into `<url>` and fixing up the hreflang support.

**Comment by jeremydw** [comment]
Fixed in https://github.com/grow/grow/commit/781094ae55829f7605e13dc8fbc6a8830644d752
