### ISSUE TITLE
`grow version` should be faster

### ISSUE THREAD

**Issue by stevenle** [grow/grow#1086]
Not sure what initialization costs are for starting up the grow command, but `grow version` seems to take an abnormally long time for something that should output really quickly.

**Comment by Zoramite** [comment]
I think the extra overhead comes from the `click` library. We are using the decorator for the version: https://github.com/grow/grow/blob/master/grow/commands/group.py#L13

One thing we could try and look into is if there is a way to dynamically load the commands so they are not all loaded. Not sure if click has that functionality though.

**Comment by jeremydw** [comment]
I looked into this a few years ago, as well. As Randy mentioned all of
Grow's modules are imported whenever a command is run (including
`--version`). I think it's the import time that's slowing down all commands.

Ideally we look into how other libraries handle this. I tried running
`gcloud --version` a few times and the first time or two were a bit slower,
and subsequent invocations were instant.
