### ISSUE TITLE
Remove `%` style placeholders in py3

### ISSUE THREAD

**Issue by stevenle** [grow/grow#1093]
Remove support for `value = value % variables` in tags.py (or add a very strong deprecation warning).

**Comment by Zoramite** [comment]
Added deprecation warning in 0bc4c79771db5f49baf37e4b90f0598a6239bdef

**Comment by Zoramite** [comment]
Do we want to drop support completely in the python 3 version of grow for the `%` formatting? We have been 'warning' about it since jun. If we are going to drop it we can add it to the list of breaking changes in migration doc.

**Comment by stevenle** [comment]
IMHO yes

**Comment by jeremydw** [comment]
Agree with dropping support for it. I wonder if we can provide folks with a
code snippet to find/replace all instances? That should be doable with a
regex, right?

**Comment by Zoramite** [comment]
We can probably suggest some regexs to find and replace some of the common instances. But there are a lot of options that can be used.

Something like `%(\([a-z0-9_]*\))?s` => `{[1]}`

**Comment by stevenle** [comment]
I would just suggest leaving it up to the developer to figure out how exactly they should migrate, and maybe just say these are examples of old vs new format:

`Hello %s` => `Hello {}`
`Hello %(name)s` => `Hello {name}`

**Comment by Zoramite** [comment]
Closed by #1132
