### ISSUE TITLE
Packaged version of grow has slow version of yaml

### ISSUE THREAD

**Issue by stevenle** [grow/grow#1094]
Only tested on Mac, but this version (https://github.com/grow/grow/releases/download/1.0.0-alpha.3/Grow-SDK-Mac-1.0.0-alpha.3.zip) seems to yield the warning below: 

```
Warning: libyaml missing, using slower yaml parser.
```

**Comment by Zoramite** [comment]
Fixed by ae689519c0df38847a75a27f2681b25920159f90
