### ISSUE TITLE
Show more descriptive error message when using the `g.static` template function with a path to a file that does not exist

### ISSUE THREAD

**Issue by jeremydw** [grow/grow#110]
`{{g.static('/path/to/file/that/does/not/exist.png').url.path}}` should show a more descriptive error message than "None does not have a property url".

**Comment by Zoramite** [comment]
This appears to already be fixed:

`Either no file exists at "/source/media/not/exists.png" or the "static_dirs" setting was not configured for this path in podspec.yaml.`
