### ISSUE TITLE
Dots in $path cause an error 'not found in static files'.

### ISSUE THREAD

**Issue by willthomson** [grow/grow#1112]
I have a case where it is a requirement to include a dot in part of the path. For example:

`$path: /{root}/an/example.path`

In doing so, I get the error:

`'/an/example.path was not found in static files.'`

**Comment by jeremydw** [comment]
@Zoramite can you investigate this?

**Comment by Zoramite** [comment]
@willthomson just to be clear, are you trying to serve at `/root/an/example.path/index.html` or as an actual file at `/root/an/example.path` ?

**Comment by jeremydw** [comment]
@Zoramite - the specific use case is we need to support a YAML configuration akin to this (imagine a website that catalogs TLDs):

```
$path: /domain-endings/co.uk/
```

`grow build` should build this page to `build/domain-endings/co.uk/index.html`

**Comment by Zoramite** [comment]
Thanks, that is what I needed to know. :)

**Comment by Zoramite** [comment]
Looking into this specific case, the `$slug` was being used in the document, but the url was using `{base}` which ignores the slug. Tested with the normal `$path` and it was working as well.. I think the reason it wasn't working in this case is that it also needed the `$localization.path` as well.
