### ISSUE TITLE
SortedCollection will not sort/compare int/None

### ISSUE THREAD

**Issue by angusm** [grow/grow#1113]
![Screen Shot 2020-07-08 at 10 40 07 AM](https://user-images.githubusercontent.com/409087/87074939-d6dd1380-c1dc-11ea-87ae-9bc35a0e1b21.png)

When grabbing documents from a collection with `g.docs` the default sort on `$order` fails if some documents have `$order: null`.

This seems to have worked prior to the python 3 changes.

**Comment by Zoramite** [comment]
Thanks, in python 2 it allowed for comparisons between `None` and numbers. But in Python 3 it doesn't let you compare them. I've updated it to make a default value (0 in for the collection ordering) that can be used for sorting when the there is a `None` value for the order.
