### ISSUE TITLE
Grow 1.0.0 Migration Guide

### ISSUE THREAD

**Issue by Zoramite** [grow/grow#1131]
Before we officially release the Grow 1.0.0 version we need to have a migration guide in place that helps users with the transition to the new changes and upgrade process.

Things that we need in the migration guide:

- [x] Pipenv instructions
- [x] Alias instructions (ex: `alias grow=pipenv run grow`)
- [x] Node version in docker images uses LTS version.
- [x] `%` based formatting removal ( pending #1093 )
- [x] Possibly lib yaml instruction ( pending #1097 )

More...?

**Comment by Zoramite** [comment]
For links in the grow code, using https://grow.dev/migration/1.0.0 as the link for the migration documentation.

**Comment by jeremydw** [comment]
Install instructions (WIP) are here: 
https://github.com/grow/grow.io/blob/feature/1.0.0/content/docs/get-started/install.md

Next step is to add the migration guide that links to these (and elsewhere)
