### ISSUE TITLE
question about $view

### ISSUE THREAD

**Issue by jaygray0919** [grow/grow#1217]
We specify `$view` in _blueprint.yaml
For example:
  `view: /views/default.j2`

For a document in target Pod, we then extend that view with a customized view like this
  `view: /views/pages.html`

Can we use 2 or more `view: /target` statements at the document level?
We realize it's our responsibility to eliminate contention among files used by views.
But if we properly segregate, can we use 2+ views at the document-level?

**Comment by jeremydw** [comment]
Documents and views have a one-to-one relationship. It's possible for you to define `$view` at the collection level (in `_blueprint.yaml`), but you can also override it at the document level by supplying `$view` inside a document file.

For example:

```
/content/foo/
  _blueprint.yaml -> $view: /views/base.html
  page1.md -> no view specified
  page2.md -> $view: /views/custom.html
```

The view for `page1` is `base.html` (provided by the collection) and the view for `page2` is `custom.html` (provided by the document).

It's not possible for a single document to have two views, but you could write a single view and then `{% include %}` multiple files inside the Jinja template.
