### ISSUE TITLE
Grow does not exit 

### ISSUE THREAD

**Issue by WillsB3** [grow/grow#149]
Hi,

Over the last week or so Grow sometimes doesn't seem to closing properly. When trying to quit Grow I get the following and am unable to exit:

<img width="668" alt="screen shot 2015-10-30 at 10 55 59" src="https://cloud.githubusercontent.com/assets/868834/10844090/050268ee-7ef5-11e5-83a3-cd6190303787.png">

Sometimes I get the twisted exception, but Grow still manages to exit:

<img width="661" alt="screen shot 2015-10-30 at 10 59 
50" src="https://cloud.githubusercontent.com/assets/868834/10844142/637e246c-7ef5-11e5-8cc6-6ef282d20026.png">

This doesn't happen if I start grow, then stop it before making a request to the development server with a browser.

The only way I am able to restart grow if this happens is to completely close the terminal tab and open a new one.

**Comment by jeremydw** [comment]
While I have indeed run into this before, I spent some time over the weekend trying to reproduce this concretely. Do you have any guidance with specific steps to reproduce this -- or is it more of a "sometimes it locks up and I need to `kill -9` it and sometimes it doesn't" kind of thing?

**Comment by WillsB3** [comment]
Yeah, I haven't worked out the pattern yet. It seems to longer I leave the server running the more likely it is to happen though.

I wonder if it's caused by refreshing the page in-browser before it's completely finished loading. In these circumstances I believe Chrome sends an ABORT signal to the server, so maybe the new development server is having issues with that? (this is just a really wild guess...)

**Comment by jeremydw** [comment]
I've made a number of improvements to the dev server this weekend that seem to have cleaned up the exit performance, but I've been able to reproduce the twisted error at least once, and I've also reproduced the following watchdog error.

Note that in both cases, the server still has exited quickly, but I'd like to avoid the ugly errors in the console.

```
^C[16:19:44] Goodbye. Shutting down.
Exception in thread Thread-1 (most likely raised during interpreter shutdown):Exception in thread Thread-5 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/Users/jeremydw/git/pygrow/env/lib/python2.7/site-packages/watchdog/observers/api.py", line 242, in run
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'Empty'

Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/Users/jeremydw/git/pygrow/env/lib/python2.7/site-packages/watchdog/observers/api.py", line 242, in run
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'Empty'
```

**Comment by WillsB3** [comment]
Yay - We got this sorted 👍
