### ISSUE TITLE
Grow extract extracts strings for non-specified locales

### ISSUE THREAD

**Issue by matthewhall** [grow/grow#157]
Looks like running `grow extract --localized` will extract all strings from a YAML for all available locales, regardless of whether they're only overridden for a particular locale or not.

For example:

```
some_key@: "Some text"

---
$locales:
  - en_au
  - en_nz

some_key@: "Some different text"
```

Running `grow extract --localized` will extract "Some different text" for all locales not just `en_au` and `en_nz`.

Thanks.

**Comment by jeremydw** [comment]
This should be fixed in `master`, now and we've got a larger tracking issue that should also be all fixed up in #204. Thanks a bunch.
