### ISSUE TITLE
Improve .bash_profile installer

### ISSUE THREAD

**Issue by somenxavier** [grow/grow#167]
Hi,

Please add `export PATH=$PATH:/home/xan/bin` to `.bashrc` or `bash_profile` in addition to
```
# Added by Grow SDK Installer (2016-01-06 19:49:02.856458)
alias grow="/home/xan/bin/grow"
```
Otherwise the `/bin/grow` is not usable.

Thanks,

**Comment by jeremydw** [comment]
Marking as a duplicate of #43.
