### ISSUE TITLE
Implement $paths

### ISSUE THREAD

**Issue by jeremydw** [grow/grow#178]
We need the ability to build a document to multiple paths. Example syntax below.

Before implementing, we need to figure out how to handle the case `{{g.doc('/content/pages/foo.yaml').url.path}}` – which path would that use? Need a way to specify the path formatter value as an argument – so need to take that into consideration when designing the feature.

```
$paths:
- /foo/
- /bar/
- /baz/
```

**Comment by jeremydw** [comment]
Here's a proposal (a bit different from $paths) but same idea:

$path: /people/{expand:name}/
$expand:
  name: ['alice', 'bob', 'carl']
  
# Now you can use:
{{g.doc('/content/pages/people.yaml', name='alice').url.path}}
{{g.doc('/content/pages/people.yaml', name='bob').url.path}}
{{g.doc('/content/pages/people.yaml', name='carl').url.path}}

# Raises an error.
{{g.doc('/content/pages/people.yaml', name='someone').url.path}}

Since $expand is its own identifier in the yaml file, you would nicely be able to localize this and also use yaml anchors/aliases to set the expansion parameters.

**Comment by Zoramite** [comment]
I think we need to getter define the use case for this. It seems you want to parameterize the document based on url variables, but it is unclear on why we would really want to do that.
