### ISSUE TITLE
Amazon S3 deployments leak full bucket information

### ISSUE THREAD

**Issue by vitorio** [grow/grow#213]
[deployments/destinations/amazon_s3.py#L57](https://github.com/grow/grow/blob/master/grow/deployments/destinations/amazon_s3.py#L57) sets an Amazon S3 bucket to "public-read", which does not set the contents to public-read, but rather allows anyone to get the full XML list of bucket contents from the non-website endpoint.

As an example, a non-website endpoint is: http://vitorio-test-grow.s3.amazonaws.com and you can see every file in the bucket from here.

A website endpoint (which Grow enables) is: http://vitorio-test-grow.s3-website-us-east-1.amazonaws.com and this is what delivers the index.html properly.

Each file is properly set to public-read elsewhere in the code.  Setting the bucket to public-read simply leaks information about the bucket unnecessarily.

A bucket without public-read set looks like this on its non-website endpoint:  http://vitor.io.s3.amazonaws.com

While the website endpoint continues to function properly: http://vitor.io.s3-website-us-east-1.amazonaws.com

**Comment by jeremydw** [comment]
Thanks for raising this. I think we should fix this by removing the code that sets public-read on the bucket, and simply ensure that public-read is set on a file-by-file basis for each file deployed to S3/GCS. Thoughts?

**Comment by vitorio** [comment]
I currently have line 57 commented out on my local and haven't experienced any deployment problems.  `write_file` does the right things.

**Comment by vitorio** [comment]
I've since updated Grow and deployed new sites to S3 and this seems to be behaving correctly, now, this can probably be closed, assuming GCS is also behaving properly.

**Comment by jeremydw** [comment]
Indeed, this was fixed in https://github.com/grow/grow/commit/4908a31355c89d06427ba4896a9f311474f9fc99. Thanks for following up on this issue; can confirm the equivalent fix was made for GCS.
