### ISSUE TITLE
Dev server doesn’t support video streaming (required by Safari)

### ISSUE THREAD

**Issue by stucox** [grow/grow#215]
AFAICT, Grow’s dev server serves videos as full assets (HTTP 200), which is fine in Chrome but Safari expects to be able to stream with partial content (HTTP 206).

The test case I have (not too easy to share I’m afraid) shows that dev server returns HTTP 200 and the video doesn’t work in Safari, while webreview and my production server both serve the same file as partial content with HTTP 206 and this _does_ work in Safari.

I can’t see any other relevant differences in the responses. Not too familiar with Safari’s dev tools, so having trouble finding out what headers it requests with!

**Comment by vitorio** [comment]
Can confirm this is a problem with audio assets, too.  Behavior looks like Grow's dev server isn't supporting range requests.

Looks like Grow's dev server is based on Twisted Web, which does support range requests (versus SimpleHTTPServer, which does not), so I'm not sure where the disconnect is.

**Comment by jeremydw** [comment]
Thanks for reporting this -- was fixed back in https://github.com/grow/grow/issues/60 but a regression occurred when we updated to use Twisted. I fixed the regression and added tests to prevent this in the future.
