### ISSUE TITLE
Feature request: Google OAuth authentication

### ISSUE THREAD

**Issue by stevenle** [grow/grow#224]
In some cases, it'd be useful to run a non-local dev server and have stakeholders review content changes regularly. This would especially be useful with @jeremydw's new preprocess `schedule` feature, where content may be regularly updated by content editors who would want to be able to preview changes as they make them. 

It'd be great to either add an option to `grow run` and/or have some setting in the `podspec` that allows you to control access to the dev server using Google OAuth (although it should be generic enough to support other OAuth mechanisms, e.g. GitHub).

**Comment by jeremydw** [comment]
Some questions off the top of my head:

1. Should this just be for the development server?
1. If not, should it be a setting one can specify on an environment or per-deployment basis?
1. What about restricting access on a per-collection/per-document basis? Similar to `$localization`. (IMO we should we table the implementation for now until there's a concrete use case.)

Just some open questions. After we figure out how to specify access control in YAML, once we get down to implementation, I have code in `grow/airlock` that we can genericize out of App Engine and use for this purpose.

As an aside, in the new webreview, you can specify access on a user and domain-level, e.g. `email: foo@example.com` (just foo@example.com) or `domain: example.com` (all users in example.com). So we should support both for this feature too. :)

**Comment by jeremydw** [comment]
BTW even if it's just for the development server, we can still hijack the `deployments` setting in `podspec` which is the place folks currently set environment properties. It might be good to start with this.

E.g.

```
deployments:
  dev:  # Environment settings for the development server go here, similar to "webreview".
    access_control:  # Access control stuff here.
      ...
```

**Comment by jeremydw** [comment]
Just thought of one more little issue ... Google OAuth requires you to specify authorized redirect URIs in the developers console. Would we have users who want to use this feature register their own Google developers project so they could specify the authorized domains, project names, etc.? Wonder if there's any way around that.

**Comment by jeremydw** [comment]
We could provide an endpoint on webreview that handles all of the OAuth requests on behalf of development servers, and then redirects to the oauth2 callback URL on each development server, passing through the data included in the `state` parameter.

http://stackoverflow.com/questions/13652062/subdomain-in-google-console-redirect-uris
http://stackoverflow.com/questions/14456821/how-to-deal-with-arbitrary-amount-of-redirect-uris

**Comment by stevenle** [comment]
A few different questions, I hope I covered all:

I intended to the scope of this FR to be just for the devserver. I see your point about reusing the `deployments` key but thinking about the current `deploy` behavior, it doesn't feel like the right place to put these settings since `grow deploy dev` wouldn't really do anything (unless `grow deploy dev` would basically be like an alias for `grow run`, but I'd be opposed to doing that). Maybe we should punt on the discussion about access control configs for deployments so we can limit the scope of this discussion?

To your point about being able to configure this behavior for different envs, maybe we could have a new flag for the `grow run` command that loads some config from a key in `podspec`, something like `grow run --config=foo`, where "foo" is loaded from:

```
devserver:
  foo:
    access_control:
      type: google_oauth
      allowed_users:
      - alice@gmail.com
      - bob@gmail.com
      allowed_domains:
      - blinkk.com
```

Re: oauth2 implementation, using webreview as a proxy doesn't seem super secure. I'm guessing the way it'd work is that the OAuth redirect would direct to webreview (which we'd whitelist the url for), and then webreview would forward the token to the grow devserver. That would mean you'd need to distribute the grow oauth2 client secret within the CLI and I don't think we should do that. I'd suggest having the user create their own client id and secret and redirect urls...but maybe I'm a little too optimistic that people don't mind going through some trouble to set this up? :)

**Comment by jeremydw** [comment]
- Okay, agree on people providing their own client secrets.
- How about just `server` instead of `devserver`? Then this would work well with the App Engine example I shared in Slack today, without any further configuration.

**Comment by stevenle** [comment]
`server` SGTM

**Comment by Zoramite** [comment]
I think we are going away from the idea of allowing access to a local server for these kinds of things. We have plenty of CI abilities that can upload things to webreview for staging. Also, if you *really* need to have someone be able to see your local dev server you can do some things with port forwarding.

I'm going to close this for now since it doesn't seem like something we want to work towards.
