### ISSUE TITLE
Flag / env var for keyring password

### ISSUE THREAD

**Issue by stevenle** [grow/grow#225]
Ran into an issue today with Google Sheets preprocessor running on Ubuntu 16.06. Since the OAuth credentials are stored in keyring, it prompts for a password whenever I run the `grow preprocess` command, and an empty password isn't allowed. I couldn't for the life of me figure out how to avoid the password prompt so I think maybe a better workaround is to have a flag or env var that sets the keyring password. Something like `--keyring_password=<password>` or `GROW_KEYRING_PASSWORD`.

**Comment by stevenle** [comment]
Actually I don't think python's `keyring` lib gives you a way to control this, so nevermind. I'll check a different way to control keyring's behavior directly, outside of grow.

**Comment by jeremydw** [comment]
I had this problem too with Sheets and OAuth on Ubuntu. Let me know what
solution you come up with.

On Wed, Jun 8, 2016 at 12:48 PM, Steven Le <notifications@github.com> wrote:

> Closed #225 <https://github.com/grow/grow/issues/225>.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/grow/grow/issues/225#event-686349044>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AAndfXrVYCUw4qo5X1UUlQCS_ipCnWDHks5qJxyJgaJpZM4IxUzA>
> .
>



-- 
jeremydw

**Comment by stevenle** [comment]
I ended up modifying the preprocessor to use file.Storage() instead, which stores credentials in a plain-text JSON file. Not secure, but I needed to get this working quick.
