### ISSUE TITLE
Autoupdater may fail depending on Python environment

### ISSUE THREAD

**Issue by jeremydw** [grow/grow#240]
```
  Please update to the newest version of the Grow SDK.
  See release notes: https://github.com/grow/grow/releases/tag/0.0.61
  Your version: 0.0.60, latest version: 0.0.61
Auto update now? [y/N]: y
Traceback (most recent call last):
  File "<string>", line 13, in <module>
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tempfile.py", line 35, in <module>
    from random import Random as _Random
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/random.py", line 49, in <module>
    import hashlib as _hashlib
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 138, in <module>
    _hashlib.openssl_md_meth_names)
AttributeError: 'module' object has no attribute 'openssl_md_meth_names'
```

**Comment by jeremydw** [comment]
Turns out our attempts to catch this issue just don't work and, while the "helpful error message is displayed," there's still a bunch of traceback that makes it hard to figure out what to do.

My hypothesis is this happens on systems that use a specific version of Python, often with Brew. More details in these search results: https://www.google.com/search?q=brew+AttributeError%3A+%27module%27+object+has+no+attribute+%27openssl_md_meth_names%27&oq=brew+AttributeError%3A+%27module%27+object+has+no+attribute+%27openssl_md_meth_names%27&aqs=chrome..69i57.864j0j7&sourceid=chrome&ie=UTF-8

The actual fix here should be to fix the autoupdater. In lieu of being able to actually fix the autoupdater in this environment, we should catch all the errors and show the update instructions cleanly.

**Comment by Zoramite** [comment]
I think that we have fixed up the auto-updater enough for this to work. At least I have not seen this error for a while.
