### ISSUE TITLE
Firebase hosting / deployment

### ISSUE THREAD

**Issue by jeremydw** [grow/grow#245]
Firebase supports free, zero-configuration SSL hosting for static web applications and content. Users can choose to deploy to `<subdomain>.firebaseapp.com` or a custom domain. We could add an integration for `grow deploy` for Firebase, or short of a direct integration, we could document steps to set up and deploy a Grow website to Firebase to make it as easy as possible.

Some docs:
https://firebase.google.com/docs/hosting/

**Comment by Zoramite** [comment]
I don't know if we need to directly build this into grow. The [ampproject/docs](https://github.com/ampproject/docs) is using firebase for their builds as part of the CI and it seems to work well without specific grow support.

**Comment by Zoramite** [comment]
I think if we still want to support this it should be done as an extension, not directly in grow.
