### ISSUE TITLE
Sitemap does not work in development

### ISSUE THREAD

**Issue by WillsB3** [grow/grow#254]
[The docs](http://grow.io/docs/urls/#sitemap) explicitly mention that sitemaps can be auto-generated upon build, but it'd be nice for it to work locally too.

<img width="868" alt="screen shot 2016-07-13 at 14 54 42" src="https://cloud.githubusercontent.com/assets/868834/16805801/ce8383b8-4909-11e6-8377-88abc250ad74.png">

Are there some technical limitations as to why the docs explicitly suggest that the sitemap will only be available after a build?

**Comment by jeremydw** [comment]
No, this looks like a bug and it should work in development. I'll look into it.
