### ISSUE TITLE
Support code block syntax using ``` code ```

### ISSUE THREAD

**Issue by bluzky** [grow/grow#270]
I think that we should support code block syntax
\`\`\` python
\# code block
\`\`\`
because this syntax is quite popular and easier to read than 4 space.
And with this syntax we can set which programming language in the code block, so that we can use some javascript library such as prism.js ... for highlighting the code block.

**Comment by jeremydw** [comment]
Great suggestion, thanks for it. Implemented this along with a test and it'll be available in the next release, which we'll make in a few days.

**Comment by jeremydw** [comment]
As an FYI, in the meantime, you can use the `sourcecode` tag, e.g.:

```
[sourcecode:python]
# code block
[/sourcecode]
```

**Comment by bluzky** [comment]
thank you
