### ISSUE TITLE
PDF generation preprocessor problems

### ISSUE THREAD

**Issue by vitorio** [grow/grow#271]
(If there's a better place to ask questions than the issues queue, please let me know and feel free to close.)

I'm trying to hack together a PDF generation preprocessor, to generate both PDF versions of Grow-rendered pages, and also to generate PDFs of things that don't have published URLs.  I'd like Grow to generate (or process from Markdown) the HTML that I pass to `wkhtmltopdf` for consistency, rather than doing it elsewhere.

It looked like it should be simple, but I seem to have run into a few gotchas, and I'd like to know if there are things I've missed.

``` python
# /extensions/preprocessors/wkhtmltopdf.py

import grow, protorpc
import pdfkit

class PDFPreprocessor(grow.Preprocessor):
    KIND = 'pdf'

    class Config(protorpc.messages.Message):
        path = protorpc.messages.StringField(1)
        out_path = protorpc.messages.StringField(2)

    def run(self, build=True):
        controller, params = self.pod.match(self.config.path.lstrip('/'))
        try:
            output = controller.render(params, inject=False)
        except:
            print 'Error building: {}'.format(controller)
            raise

        pdfkit.from_string(output, self.config.out_path)

        print 'Wrote PDF -> {}'.format(self.config.out_path)
```

First, `path` as expected by `pod.match` needs to be a URL route, not a document path, which means I can't generate PDFs from invisible/hidden documents.

Second, all the CSS/etc. paths generated by the Grow/Jinja2 templates are relative to the URL serving location, not to the filesystem, which means `wkhtmltopdf` can't find them.  For these templates, I guess I'd need everything to have absolute paths to the local filesystem, but that's not available in the stock Jinja2 environment (`grow.ui` provides `pod.root` specially for its rendering, which sometimes is the local filesystem).

Third, having a custom template for invisible/hidden documents is fine, but for public documents that are served at a URL, I kind of want #178 but also with multiple views per document.  That is, I'd need to be able to specify a PDF rendering view in a variable that the preprocessor could get to, and I haven't tried getting to that data yet.

What should I be looking at to solve these?  I'm not sure about the first at all.  For the second, maybe I can pull the code out of `rendered.render` and make some special PDF rendering variables for a custom template?

**Comment by Zoramite** [comment]
A couple of thoughts:
- I'm not sure how you are configuring your extension, but if you are pointing it at a directory of docs that you want to convert, instead of using the `pod.match` you can skip directly to creating a [controller for rendering](https://github.com/grow/grow/blob/4b7e9ec81ad36153857211b73d1e755007411074/grow/pods/routes.py#L81-L82) either from a `pod.get_doc` or using a collection to `list_docs`.
- One hacky idea to try and fix the css/paths. If they are paths like `/styles/style.css` you could do a find/replace on the generated html before you pass it to the pdfkit to add a base tag: `<base href="/path/to/pod">` and use the `pod.root` just inside the `<head>` tag. I'm not sure if that is compatible with pdfkit, but it would be nice if it were. Or maybe pdfkit has a way to pass some kind of base path to look for files in?

**Comment by Zoramite** [comment]
@vitorio Did you get this working? It sounds like an interesting idea to have an extension that would generate pdfs for you.

If you feel up to it we can put together an repo for an extension and see if we can get it to work correctly to generate a pdf.

As part of the experimental `--re-route` we have access to a post-processor hook that would be able to run after a doc is rendered. We may be able to use that with some string replacement of urls to correctly generate pdf using the pod root to expand it out. And we would need to figure out how to get it into the rendered docs to be done as part of the deployment. But I think those would be doable.

**Comment by vitorio** [comment]
At the time, I wasn't able to figure it out, no.  I ended up generating the PDFs manually, outside of grow, and just deploying them like regular static files.  I agree that being able to generate PDFs in an extension would be nice!  I may be getting back to this soon for another deployment, but no guarantees and no ETA.
