### ISSUE TITLE
Path formatters in $view

### ISSUE THREAD

**Issue by stevenle** [grow/grow#275]
e.g. `$view: /views/{base}.html` within _blueprint.yaml.

**Comment by jeremydw** [comment]
This should've been implemented back in https://github.com/grow/grow/commit/870086bbb2ef429890f2e322e425ac46b5909abc -- will add an explicit test to cover.

**Comment by jeremydw** [comment]
Let me know if this isn't sufficient or if this isn't working in some particular place.
