### ISSUE TITLE
Inlining resources

### ISSUE THREAD

**Issue by mhchen** [grow/grow#276]
We could definitely use a way to inline resources like SVGs. I like what [gulp-inline-source](https://github.com/fmal/gulp-inline-source) has done, and maybe we could do something similar by adding g-inline e.g.

```
<img src="/foo/bar.svg" class="logo" g-inline>
```

being converted to

```
<svg class="logo">
...
</svg>
```

I don't see this being that useful for anything other than SVG or inlining critical CSS in the <head>, but for those purposes it would be very handy. What do you think?

**Comment by stucox** [comment]
You can just `{% include %}` an SVG file from wherever it is in your pod... so not sure if Grow really needs any special functionality for this.

I've done this quite a lot on projects quite successfully!

**Comment by mhchen** [comment]
Thanks Stu! My example includes transferring the attributes from the HTML
element into the included element though, so this doesn't solve that use
case. One of the main reasons I want to do this at all is to have the
ability to target individual fill colors using CSS

**Comment by stucox** [comment]
I personally wouldn't bother having the HTML elem in the first place :) Just include the SVG, and use [`with context`](http://jinja.pocoo.org/docs/dev/templates/#include) if you need to pass params:

```html
{% with class="logo" %}
  {% include "foo/bar.svg" with context %}
{% endwith %}
```

```svg
<svg class="{{ class }}">
    ...
</svg>
```

**Comment by mhchen** [comment]
That sounds like a solution, but I'd rather not do that. The plugin I
linked has 8000+ downloads last month so this is clearly a useful concept.

**Comment by stucox** [comment]
You can of course use add `gulp-inline-source` to your Grow project and preprocess your templates prior to building...

Or is there a reason why this is difficult / undesirable?

Apologies for the resistance, but IMO we should keep Grow as lean as possible and make use other libraries where necessary, rather than developing Grow into a monolithic platform which aims to be all things to all people.

**Comment by mhchen** [comment]
That seems like a much worse alternative as you now need to have your
templates in the dist directory.

It's 2016, and we use (and should use) SVG a lot now. I don't really see
why this should be an uncommon use case.

I saw your comment on the partials and I'm inclined to agree. I don't agree
about this one. Features like this come with the territory of a static site
generator: it's annoying to preprocess your HTML before it runs through the
actual generator. It's the reason why projects like Hexo and Jekyll have
plugin systems, rather than just relying on the outer ecosystem of tools. I
also agree with your concept that Grow should remain small. I would gladly
write this as a plugin and it would be a great candidate for removing
if/when Grow does end up getting a plugin system, but there's no plugin
system yet, and in the meantime I think the need remains.

**Comment by jeremydw** [comment]
Thanks for hashing this out guys. This is actually what Grow's extension (plugin) system is for — evaluating features before building them into the system or for extending functionality on a project-by-project basis.

@mhchen – we have an extension system that @stucox actually designed and implemented, so all players on this thread are providing very valuable input. Sorry if it wasn't obvious enough in the documentation (we need to work on it).

https://grow.io/docs/extensions/

It's a minimal extension system but it's worked remarkably well. The system allows folks to author Jinja environment extensions and preprocessors on a project-by-project basis. Feel free to ping me if you'd like me to walk you through it or have any questions about it.

I haven't looked into the implementation details of `gulp-inline-source`. Would Jinja environment extensions or Grow preprocessors be sufficient for implementing a resource inlining plugin? It seems like Jinja extensions would be a good candidate for this?

As a point of reference I've used `{% include %}` against SVGs to incorporate them directly into HTML. You can `{% include %}` stuff from the `source` dir without needing to dump it to `dist`.

**Comment by Zoramite** [comment]
Closing this issue since there doesn't seem to be anything directly in grow we need to add. Extensions would help a lot with this to make it work well and be easy to add to projects.
