### ISSUE TITLE
Correct way to upgrade GROW in Linux

### ISSUE THREAD

**Issue by NetLancer** [grow/grow#277]
There's a latest 0.66 version installer posted for download, while originally I've got GROW SDK (older version) via - curl https://install.growsdk.org | bash - command. Should I just download & run the installer file or again use the command above in terminal (my case is linux mint) ?
Sorry guys, I'm a newbie to GROW SDK and python things :)

**Comment by jeremydw** [comment]
Hi @NetLancer — that's right. Go ahead and use the same install command to update if you are using the installer. That should do the trick. If you are installing via `pip` you can use the `--upgrade` flag.

I'll close this issue out for now but please feel free to send over any other questions.
