### ISSUE TITLE
Templating tags for page layout customization

### ISSUE THREAD

**Issue by NetLancer** [grow/grow#282]
Here I need to modify page layout in terms of division of 'main' section into few columns as needed (for sidebar or tiled view etc). I wonder if there's a way to achieve it with tags like {{ columns 3, 1 }} just like http://www.sitebox.io/articles/columns-method provides (they use scribble templating as far as I know) but it is very handy. I'd prefer this method (if there is) to writing bunch of ugly html.

**Comment by WillsB3** [comment]
Hi,

Grow uses [Jinja2](http://jinja.pocoo.org/docs/dev/) for templating ([template docs here](http://jinja.pocoo.org/docs/dev/templates/)). 

While there's nothing like this pre-built, you could write [Jinja macros](http://jinja.pocoo.org/docs/dev/templates/#macros) to generate the HTML you need for your columns. 

Grow also provides the ability to use custom [extensions](http://grow.io/docs/extensions/) for Jinja, so you could potentially write an extension to add support for the sort of syntax you mention.

**Comment by jeremydw** [comment]
@WillsB3 is right -- you can easily write Jinja2 templates to customize the presentation of your website, including adding the ability for you bind data to your layout and use data in your yaml to determine what kind of layout to show. The grow default theme "base" shows you one way to do this:

https://github.com/growthemes/base/blob/master/content/pages/home.yaml#L7
https://github.com/growthemes/base/blob/master/views/partials/hero.html

**Comment by jeremydw** [comment]
But, let us know if you have any questions or code to share and we can take a look and provide advice!
