### ISSUE TITLE
g.url ignores branch name

### ISSUE THREAD

**Issue by lucasdupin** [grow/grow#295]
Hi all,
I think I found a bug related to absolute URL generation.

Currently I have a code snippet, on a template, that looks like this:

```html
<a href="{{ g.url('/content/main/my_page.yaml') }}">link</a>
```

Locally the URL it generates looks fine: `http://localhost:3000/my_page/`.
But if I deploy a feature branch using `grow stage`, the server name gets prepended by `none`. 

Current output: 

```
none-dot-googwebreview.appspot.com/mypage
``` 

Expected output: 

```
branch-name-dot-googwebreview.appspot.com/mypage
```

My grow version is **0.0.66**

Thanks!

**Comment by jeremydw** [comment]
Thanks for reporting this -- fixed in b97833954692c39ff4641c8f31a7abc3b885ee00 and will be released in the next release.
