### ISSUE TITLE
g.categories doesn't support recursive=false

### ISSUE THREAD

**Issue by pbakaus** [grow/grow#309]
I'd like to use categories in my site nav, in addition to the collection based hierarchy. However, while you can do the latter with `doc.collection.docs(recursive=false, locale=doc.locale)`, g.categories supports no `recursive` argument.

That means that all sub docs will be mashed together and flattened in the categorized list, which isn't what I want.

**Comment by jeremydw** [comment]
@Zoramite Could you look into this? We have a method on the `Collection` object which should support a `recursive` argument.
