### ISSUE TITLE
Add additional system columns to Google Sheets translations

### ISSUE THREAD

**Issue by jeremydw** [grow/grow#313]
Currently, Google Sheets translations contain two columns:
1. source language
2. translated language

We should add additional columns that contain more information from the PO files. The additional columns should be:
- location
- obsolete

With "location" containing a list of locations from the PO file, and "obsolete" a true/false field containing whether the string is obsolete.

In the below example PO file, `/content/pages/home.yaml` would be the value for `location`.

```
#: /content/pages/home.yaml
msgid "A basic Grow demo website."
msgstr ""

#: /content/pages/about.yaml
msgid "About"
msgstr ""

#: /content/pages/about.yaml
msgid "About this project"
msgstr ""
```

Here is where Google Sheets column data is set:
https://github.com/grow/grow/blob/master/grow/translators/google_sheets.py#L174
https://github.com/grow/grow/blob/master/grow/translators/google_sheets.py#L196

**Comment by Zoramite** [comment]
What is the determination of if a field is "obsolete"?

**Comment by jeremydw** [comment]
Babel Catalogs have an internal way of collecting obsolete messages – https://github.com/python-babel/babel/blob/master/babel/messages/catalog.py#L719 – but in Grow projects, we find this is not oft-used.

For the purpose of Google Sheets-based translations, we should mark messages as obsolete if they're present in the last-uploaded worksheet, but NOT present in the local message catalog that is being uploaded. Those messages should be maintained and stored in the Google Sheet (and indicated with an "obsolete" column), in case they need to be referenced when doing translation work or are later used again and are no longer obsolete.

The obsolete messages should not be downloaded locally unless `--include-obsolete` is used. If this flag doesn't currently exist as part of the download command, we don't need to implement it now.

LMK if you need any extra clarification and we can chat!

**Comment by Zoramite** [comment]
The lack of location information seems to be a better indication of the obsolete messages. I tried to use the catalog's obsolete messages, but it didn't act like I was expecting.

Alternatively, I would like to use some custom formatting for highlighting the ones that are obsolete (missing location), instead of a separate true/false columns.

**Comment by jeremydw** [comment]
I see; the Babel Catalog's obsolete messages are less important than the messages that existed in the Google Sheet but no longer exist in the local catalog. Those are the ones that should be preserved in the sheet but marked as obsolete in some way.

Custom formatting sounds great. There is a way to do conditional formatting in the Google Sheets API. I think rows that are obsolete should have a grey background.

**Comment by Zoramite** [comment]
I am doing a pull request for the location column and the ability to include obsolete messages in the upload. I'll do a separate issue for the formatting of the spreadsheet since it wasn't working in my original attempt.

**Comment by Zoramite** [comment]
Closed by #316

**Comment by jeremydw** [comment]
I just noticed that the change isn't exactly backwards compatible with the two-column sheets. Would you mind adding backwards compatibility if the "location" column doesn't exist?

```
  File "/Users/jeremydw/git/grow/bin/../grow/translators/google_sheets.py", line 63, in _download_content
    source_lang, lang, _ = values.pop(0)
ValueError: need more than 2 values to unpack
```

**Comment by Zoramite** [comment]
This should be compatible now with some of the other changes.
