### ISSUE TITLE
Translate does not work with jinja2 jsonify

### ISSUE THREAD

**Issue by drGrove** [grow/grow#315]
Attempted code (from growthemes/scaffold):

```html
<pre>{{ _(doc.ctas) | jsonify }}</pre>
```

In an attempt to create translated JSON, I noticed that this throws a the following error:

`unhashable type: 'list'`

Is this something that can be fixed, or is this a limitation in grow?

**Comment by jeremydw** [comment]
What is `{{doc.ctas}}`? Gettext (`_`) should only be used against strings.

**Comment by drGrove** [comment]
@jeremydw, thanks for the quick chat. 

We're trying to translate the list from [here](https://github.com/growthemes/scaffold/blob/master/content/pages/home.html#L11) for reference.

After some discussion, this was the outcome.

We are piping into [deeptrans](http://grow.io/docs/templates/#deeptrans), then piping into jsonify with ensure_ascii=False (since this example is Japanese unicode), followed by piping into safe.

Final code looks like this:

```html
<pre>{{ doc.ctas | deeptrans | jsonify(ensure_ascii=False) | safe }}</pre>
```

Giving the output:

```json
[{"subtitle": "説明1。", "title": "吹き出し1"}, {"subtitle": "説明2。", "title": "吹き出し2"}, {"subtitle": "説明3。", "title": "吹き出し3"}]
```
