### ISSUE TITLE
FR: Wildcard localized keys

### ISSUE THREAD

**Issue by stevenle** [grow/grow#319]
I find myself doing this a lot when EN source strings change, but translations aren't ready yet:

```
foo@: Old text
foo@en: New text
foo@en_CA: New text
foo@en_GB: New text
...
```

Any chance something like this might be possible or useful?

```
foo@: Old text
foo@en: New text
foo@en_*: New text
```

**Comment by jeremydw** [comment]
Yes. That's a much better way to do the syntax than what I was thinking before (e.g. `en_` for language en and `_CA` for country CA). I like the wildcard syntax a lot as it's much clearer.
