### ISSUE TITLE
Error tracebacks

### ISSUE THREAD

**Issue by stevenle** [grow/grow#341]
I just installed grow from HEAD on a new machine and I noticed that the error tracebacks (or maybe the Jinja2 errors) are no longer being rendered, not even in the terminal. Did anything change recently with the way errors are handled and displayed?

Screenshot:

![screen shot 2016-11-08 at 11 24 16 am](https://cloud.githubusercontent.com/assets/387282/20113657/27fa5dc4-a5a6-11e6-8355-df47e74593c5.png)

**Comment by jeremydw** [comment]
I was also able to reproduce this, but not consistently. I'm not sure why this started appearing. @Zoramite any of your recent changes in HEAD might have caused this? Nothing looked like it would to me but wondering if you might have a clue.

**Comment by Zoramite** [comment]
I haven't changed anything that deals with the templating or errors.

**Comment by jeremydw** [comment]
Yeah, didn't think so. We'll poke around a bit.

**Comment by Zoramite** [comment]
@stevenle This hasn't been happening anymore has it?

**Comment by stevenle** [comment]
Been using the latest `grow` and errors have been correctly reported. Closing out now.
