### ISSUE TITLE
Is there a way modify markdown to html transformation?

### ISSUE THREAD

**Issue by erwinmombay** [grow/grow#352]
Is there a way to currently override the output html that is generated? We would like to do some minor transformation on headers

**Comment by jeremydw** [comment]
There's not currently a way to extend Markdown (beyond monkeypatching Grow with an extension) - but you can pipe the markdown content to a Jinja2 filer or a separate Jinja2 extension.

We're tracking the addition of Markdown extensions here – https://github.com/grow/grow/issues/328

Until that's done, my recommendation would be to add a Grow Jinja2 extension that can search for content (say, some special indicator or identifier), and regex replace (for example) as necessary.

Let me know if you'd like some additional direction or need some pointers, here are the docs on Grow extensions – http://grow.io/docs/extensions/#jinja2-extensions

**Comment by Zoramite** [comment]
With the experimental `--re-route` option there is now the ability to write extensions that can do post-rendering modifications. For example, the [html minification](https://github.com/grow/grow-ext-html-min) of a rendered doc.

You could use this same extension hook to modify the html that is generated.

There is also [an issue](https://github.com/grow/grow/issues/328) for allowing extensions to add their own markdown extensions that is being tracked separately.
