### ISSUE TITLE
Header ID generation ignores non-roman characters

### ISSUE THREAD

**Issue by bpaduch** [grow/grow#360]
The auto-generated of heading IDs ignores non-roman characters, so, if the heading doesn't include any roman characters, the auto-generated id is a number. However, if the heading contains any roman characters, it uses those as the auto-generated id---and only those characters as the id.

**Example**: On this page - https://www.ampproject.org/ko/docs/guides/debug/validate, the first H2 has an id="amp" because the only roman characters in that heading is "AMP". Subsequent headings that do not have any English in them have numeric IDs.

Unfortunately, this issue has an impact on our content because the AMP page validation fails if a heading id contains just "amp" -- "The attribute 'id' in tag 'h2' is set to the invalid value 'amp'.

**Expectation**: The auto-generated ID should be the same as the heading title (in whatever language) . If that cannot be done, use numerics for all IDs for any non-English language.

**Comment by jeremydw** [comment]
Just so we get a little more information about this, by auto-generated ID are you referring to the Markdown-generated `id` attribute for header elements in Markdown documents? Thanks!

**Comment by bpaduch** [comment]
These are the heading IDs that are generated from the markdown into HTML.  The markdown files do not have any specified ID but have headings, and the grow build process generates anchor IDs for each heading.


- English version: MD file [validate.md](https://raw.githubusercontent.com/ampproject/docs/master/content/docs/guides/debug/validate.md) | [generated HTML file](https://www.ampproject.org/docs/guides/debug/validate)
- Generated heading tag with id `<h2 id="how-do-i-check-if-my-page-is-valid-amp">How do I check if my page is valid AMP?</h2>`
- Korean version: `<h2 id="amp">내 페이지가 유효한 AMP인 지 어떻게 확인하나요?</h2>`
