### ISSUE TITLE
Segmentation fault (core dumped) 0.0.68

### ISSUE THREAD

**Issue by thejohanmagnusson** [grow/grow#363]
Did a fresh setup of Ubuntu 16.04 LTS and Grow 0.0.68 but get a segmentation error.

```
leonid@Leonid-m2m:~$ grow
Segmentation fault (core dumped) 
leonid@Leonid-m2m:~$ 
```
`
feb 03 14:07:09 Leonid-m2m kernel: grow[5122]: segfault at 0 ip 00007fa5bb17bb96 sp 00007ffcdeddf838 error 4 in libc-2.23.so[7fa5bb0f1000+1bf000]
`

Any hint on how to solve this or if it's a bug?
I'm quite new to Linux so my knowledge is a little limited a the moment, but I'm working on it :-)

**Comment by Zoramite** [comment]
This sounds like #305 resurfacing.

**Comment by heatherbooker** [comment]
I think [this issue](https://github.com/grow/grow.io/issues/31) raised at grow/grow.io might be the same thing - I haven't seen it say 'core dumped' but I am getting 'segmentation fault'.

**Comment by Zoramite** [comment]
@thejohanmagnusson We just released some a new version that was built on a CI server. From the testing that I did I don't get the segmentation fault anymore on ubuntu. Is this still an issue for you on the latest version?

**Comment by Zoramite** [comment]
Marking as closed for now, if you are still having issues feel free to reopen.
