### ISSUE TITLE
ButterCMS Integration

### ISSUE THREAD

**Issue by mmccoy** [grow/grow#377]
In this brave new world of headless CMS, I have started to tinker with [ButterCMS](http://www.buttercms.com) and so far I'm a fan. Its simple, lean and feature-rich -- specifically with regard to image management and third-party service integration.

I'm guessing you guys are already aware of it given your realm of expertise, and the contentful theme you've put out there.

What are your thoughts on some level of integration?  I'd volunteer to work on it, as long as you could guide me to the right form for it to take (a dedicated theme? a preprocessor?, etc)

Thanks!

**Comment by Zoramite** [comment]
Hi @mmccoy !

I think that this would be similar to our integration with contentful and could be done as a preprocessor:

https://github.com/grow/grow/blob/master/grow/preprocessors/contentful_preprocessor.py

**Comment by Zoramite** [comment]
Closing this issue as we are separating out this type of integration into extensions. As an example, see the contentful extension for an example:

https://github.com/grow/grow-ext-contentful
