### ISSUE TITLE
Language switcher URL issue

### ISSUE THREAD

**Issue by lswest** [grow/grow#379]
I've taken over the language switcher setup from the codelab theme, and simply changed it to be an unordered list, instead of a select field.

I'm only using 2 languages - en and de. It's been working fine for a few days, but since creating a few `@de.md` content files containing nothing but a bit of markdown text has resulted in the menu not working properly.

The issue is essentially that when in the de locale, the menu does not strip out the de locale from the url.path. It works fine on the homepage, just not on pages where I've translated the text using a `contact@de.md` format
English (default) menu links
```
/de/kontakt
/contact-us
```
German menu links
```
/de/kontakt
/de/contact-us
```
Is this just unsupported the way I'm doing it, or do I need to define something differently?

List of files
```
_blueprint.yaml
contact@de.md
contact.md
index.md
it-services@de.md
it-services.md
projects@de.md
projects.md
qualifications.md
technologies@de.md
technologies.md
web-development@de.md
web-development.md
```

**Comment by jeremydw** [comment]
I think you'd just have to update `$path` for the blueprint to ensure the right localized path format is always used. If you're having trouble, feel free to invite me to a repo and I can take a look and provide advice.

**Comment by lswest** [comment]
I can invite you to join the repository, but it's hosted privately on GitLab.  In case that poses an issue, I've included the contents of the blueprint file below.

The _blueprint.yaml file in content/pages contains the following:
```
path: /{slug}/               # The URL path format.
view: /views/pages.html      # The template to use.
title: Pages                 # Collection's title.

localization:
  path: /{locale}/{slug}/    # Localized URL path format.
```

**Comment by jeremydw** [comment]
That should be fine as long as you're comfortable with it. Or you can
mirror it on GH. My GitLab is jeremydw@gmail.com.

**Comment by lswest** [comment]
Invite has been sent.  Thanks!

**Comment by jeremydw** [comment]
Found the issue. See the patch below. The reason why it was not working in your example is because when you use the file-based localization e.g. `<file>@<locale>.<ext>` you cannot construct other localized documents based on the current document's pod path.

The right way to do it is to use the `localize` method on the Document object. This should fix it up for you. See the patch below.

```
--- a/data/www/views/_header.html
+++ b/data/www/views/_header.html
@@ -18,7 +18,7 @@
     <ul>
       {% for locale in doc.locales %}
       <li><a{% if doc.locale == locale %} class="active"{% endif %}
-        href="{{g.doc(doc.pod_path, locale=locale).url.path}}">
+        href="{{doc.localize(locale).url.path}}">
           {{locale.get_display_name(locale)}}
       </a></li>
       {% endfor %}
```

Apologies if this wasn't clear, we're working on a docs refresh and will incorporate these instructions in the new documentation site. It also seems we should update our `base` theme with this fix. :) Let me know if this solves things for you. Thanks for checking out Grow!

**Comment by lswest** [comment]
That's fixed it for me. Thanks for solving it so quickly! So far, Grow has been absolutely terrific.
