### ISSUE TITLE
Document changes are delayed in rendering

### ISSUE THREAD

**Issue by stevenle** [grow/grow#391]
Just started using `0.1.0` and noticed changes to a document aren't refreshing until dev server is restarted.

Example document:

```
- partial: foo
  class: section--foo
```

Partial:

```
<div class="section{% if partial.class %} {{partial.class}}{% endif %}"></div>
```

I'm not sure how widely this affects other projects, only tested in MBG. I'm using the pre-built binary for Mac that was deployed Thursday (Apr 6) night on the releases page.

**Comment by Zoramite** [comment]
Further investigation show that this is actually a delayed change. The podcache is being reset in between each file change which is also rebuilding the entire routing tree. On small sites this is not an issue, but on larger sites this is a large delay.
