### ISSUE TITLE
AttributeError: 'module' object has no attribute '_base' with beautifulsoup4 4.4.0

### ISSUE THREAD

**Issue by hieu-n** [grow/grow#393]
I install grow by `pip install`:

```
$ pip install grow
$ # or 
$ pip install https://github.com/grow/grow/archive/master.zip
```
then run:
```
$ grow --help
Traceback (most recent call last):
  File "/home/miniconda2/envs/flecom/bin/grow", line 34, in <module>
    from grow.common import ca_certs_locater
  File "/home/miniconda2/envs/flecom/lib/python2.7/site-packages/grow/__init__.py", line 12, in <module>
    from .pods.pods import Pod
  File "/home/miniconda2/envs/flecom/lib/python2.7/site-packages/grow/pods/pods.py", line 3, in <module>
    from . import catalog_holder
  File "/home/miniconda2/envs/flecom/lib/python2.7/site-packages/grow/pods/catalog_holder.py", line 10, in <module>
    from grow.common import utils
  File "/home/miniconda2/envs/flecom/lib/python2.7/site-packages/grow/common/utils.py", line 9, in <module>
    import bs4
  File "/home/miniconda2/envs/flecom/lib/python2.7/site-packages/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/home/miniconda2/envs/flecom/lib/python2.7/site-packages/bs4/builder/__init__.py", line 314, in <module>
    from . import _html5lib
  File "/home/miniconda2/envs/flecom/lib/python2.7/site-packages/bs4/builder/_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: 'module' object has no attribute '_base'
```

Upgrading to the latest beautifulsoup4 fixes the problem.

```
$  pip install --no-cache-dir --upgrade beautifulsoup4
Collecting beautifulsoup4
  Downloading beautifulsoup4-4.5.3-py2-none-any.whl (85kB)
    100% |████████████████████████████████| 92kB 1.1MB/s 
Installing collected packages: beautifulsoup4
  Found existing installation: beautifulsoup4 4.4.0
    Uninstalling beautifulsoup4-4.4.0:
      Successfully uninstalled beautifulsoup4-4.4.0
Successfully installed beautifulsoup4-4.5.3
$ grow --help
Warning: libyaml missing, using slower yaml parser.
Usage: grow [OPTIONS] COMMAND [ARGS]...

  Grow is a declarative file-based website generator. Read docs at
  https://grow.io. This is version 0.1.0.
....
```

So I think we should change the beautofulsoup4 version in `requirements.txt` file.

**Comment by Zoramite** [comment]
Thanks for the feedback @hieu-n 

I have a [branch](https://github.com/grow/grow/compare/feature/update-dep) that I started this weekend to update all the deps. I need to update one of the related projects as well and maybe make some more tweaks, but hopefully over the next couple of days I'll have the dependencies up to date with the latest.

**Comment by hieu-n** [comment]
Also about `Warning: libyaml missing, using slower yaml parser.`
For Linux/Ubuntu users, that can be fixed by:

```
$ sudo apt-get install -y libyaml-dev
$ pip install --upgrade --force-reinstall pyyaml
```

I'm not sure that has been already mentioned else where.

**Comment by Zoramite** [comment]
Thanks. When we do the release builds for pip my understanding is that the release binary packages the libyaml so the libyaml should only be an issue when you are installing from master or from the cloned repo.

I've added the upgrade command to our make file so that people using a cloned version can get the benefit of the faster parser.

**Comment by hieu-n** [comment]
@Zoramite Thanks for your support. 

I have an unrelated question, but I think I shouldn't start a new issue, so I just ask it here:

I see `@` often being used in variable names, such as: `$title@` and `nav@` (https://raw.githubusercontent.com/growthemes/codelab/master/content/pages/index.md). What is their purpose?

**Comment by Zoramite** [comment]
@hieu-n That is to mark the field for translation: http://grow.io/docs/content-localization/#front-matter-localization
