### ISSUE TITLE
Warning when checking for updates

### ISSUE THREAD

**Issue by jeremydw** [grow/grow#401]
When using `grow run`, the built version of Grow is unable to check for updates and shows the following warning:

```
[Errno socket error] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661) Unable to check for the latest version: [Errno socket error] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)
```

**Comment by coryphwang** [comment]
I've run into the exact same error message. Any ideas about what we can do to resolve this?

**Comment by jeremydw** [comment]
Yep - we'll have this fixed for the next release. It only happens with the binary built on Circle CI, on Mac, when the development server checks for updates. It is fine to ignore the warning. Sorry about the log spam, though!
