### ISSUE TITLE
Cli, Grow command unknown

### ISSUE THREAD

**Issue by jel111** [grow/grow#404]
fish: Unknown command 'grow'
After using the curl command to install the next step is to run grow I get the above. Updated from 2.7 to newest version of Python still the same.

**Comment by jeremydw** [comment]
The curl installer will add an alias to your `.bashrc` for the `grow` binary in `$HOME/bin`. You'll need to either restart your Terminal window or re-source your `.bashrc` file to acquire the alias.

Does it still fail after trying either step?

**Comment by jel111** [comment]
It still fails after restart. The second option I don't understand but am trying to find out how. Thanks.

**Comment by NetLancer** [comment]
I'm having just the same problem, despite the fact I've just installed the latest 0.1.3 version ok. But plse inform what should .bashrc file look like (in my case there's no 'grow' mentioned at all)  ?

**Comment by NetLancer** [comment]
People, does anyone knows the solution to share ? Generally it would be nice if grow checks for the alias written down properly on installation or upgrade and at least notifies.
I have this in my '~/.profile'
alias grow="/home/user/bin/grow"  from previous installation but this doesn't work('Command not found')

**Comment by NetLancer** [comment]
Generally why is that so hard to get answered with a tiny question (perhaps as long as it is of non-programmer sort), i believe community support should be much better at all.
So I've get solved mine (on debian 8.8) - just in case another dummy needs:
Basically it was about '~/.bashrc' file to be added directory needed, 
thanks to resource https://www.tecmint.com/set-path-variable-linux-permanently/

**Comment by Zoramite** [comment]
@NetLancer sorry for the trouble getting a response.

For most linux distributions the `~/.bashrc` file is the correct place for the alias to be added. Some distributions also have a `~/.bash_aliases` file that is included into the `.bashrc` file if it exists.

The [installer](https://github.com/grow/grow/blob/master/install.py#L91-L107) attempts to find the correct bash file based on what your [system is using](https://github.com/grow/grow/blob/master/install.py#L55-L67). On linux it looks in this order: `.bash_profile`, `.profile`, `.bashrc`. (Note: I [just added](https://github.com/grow/grow/commit/280a840b3bf23c721d160b6658532455bfaf8c16) `.bash_aliases` as another valid place for the alias.)

As for debugging this, it does seem odd that people are having trouble with the grow command not existing. One possible issue is that the grow binary is at a different location than where the original installer added the alias to. In your case it appeared to be pointing at `/home/user/bin/grow`. Does that file actually exist? It is possible that the path to the grow binary has change in which case the alias would need to be updated. I've added a new issue to show a warning if there is a [conflicting alias](https://github.com/grow/grow/issues/416).

Another possibility is that there are multiple aliases in the different config files. I've [opened an issue](https://github.com/grow/grow/issues/417) to make the alias search more comprehensive.

**Comment by Zoramite** [comment]
I'm going to close this issue for now. The latest version of the grow installer does more checking for existing aliases and should hopefully clear up this issue. If you are past `0.1.5` and it it still having issues feel free to reopen.

**Comment by valgalin** [comment]
Hello, I'm also getting this error when doing the `curl https://install.grow.io | bash` installation option. I'm using Ubuntu 18.04. When I run `grow init base new-grow-site`, it says that grow command not found. Even after restarting terminal.

The solutions above are somewhat not direct but it guided me to the fix that worked on my end (thanks @NetLancer ). In case someone will still get this issue, what I did was run this command after doing the curl command:

`source <path to your ~/.profile or equivalent>

For example, `source /home/user/.profile`

You will know the correct path to the bash file because after the curl command, the installer will tell you where the grow alias was created.

**Comment by Zoramite** [comment]
@valgalin did the `.profile` file exist before you ran the installer? It should only add it to the profile file if it exists and my understanding is that file doesn't exist by default in ubuntu, but I could be mistaken. Usually it has a `.bashrc` file in ubuntu that is used to initialize the base sessions.
