### ISSUE TITLE
Update installer to check multiple bash files for grow alias

### ISSUE THREAD

**Issue by Zoramite** [grow/grow#417]
Currently the installer checks only one bash config file for a grow alias. An improvement would be to search all existing config files for the alias to make sure they are not conflicting aliases.

Additionally it should check for multiple occurrences of the grow alias across all the config files to show a warning if it exists in multiple places.

**Comment by jeremydw** [comment]
How does the new Google Cloud SDK work? The original code for Grow was based on how gcloud registered itself. There have been several changes/updates to gcloud SDK since, so I'm wondering if we can look at how gcloud works these days and do that too.

**Comment by Zoramite** [comment]
Looks like gcloud does this:

```bash
# The next line updates PATH for the Google Cloud SDK.
if [ -f /Users/randy/google-cloud-sdk/path.bash.inc ]; then
  source '/Users/randy/google-cloud-sdk/path.bash.inc'
fi
```

**Comment by Zoramite** [comment]
Also, their install script is very complex, I was digging into a bit. I don't think we'll be able to copy exactly what they do, but I think I have a nice solution for now.

**Comment by jeremydw** [comment]
Sounds good, I just took a look at your solution and it looks like it'll cover the situations we care about when using the installer, so that's looking good.
