### ISSUE TITLE
Explore Filter Views for Translation Spreadsheets

### ISSUE THREAD

**Issue by Zoramite** [grow/grow#423]
Often when working with translations it is good to be able to filter down to just the strings from a specific page. ex: `/content/pages/about.yaml` and see which ones have not been translated yet. A filter view may make this process easier.

Using a filter view allows the user to filter, but does not affect how others see the spreadsheet. (Filters affect everyone looking at the sheet)

**Comment by jeremydw** [comment]
A way to allow people to do this on a per-user basis without affecting all viewers would be perfect! Some more exploration could be done with "Add ons" (using Google Apps Script) that create a sidebar as well.
