### ISSUE TITLE
Install script feedback

### ISSUE THREAD

**Issue by stevenle** [grow/grow#43]
- install.growsdk.org should 302 to a URL that ends in .sh. That way, if I save the file locally instead of piping it to bash, it'll show as "<filename>.sh" instead of "index.html". (Alternatively, setting a Content-Disposition header might work but I haven't tested.)
- Install location should be configurable. For example, I prefer to install at /usr/local/grow.
- On Ubuntu, adding .bash_profile ignores .profile (the default), which means the more common .bashrc is never sourced.
- I think it's better to add $GROW/bin to $PATH than to create an alias. If you create additional binaries, it'll automatically be available if you add it to $GROW/bin.

**Comment by fotinakis** [comment]
Per discussion, we think the right way to fix the path problems is to just download the binary into /usr/local/bin/grow and then chmod it to 777. That will let all users use it, and let them upgrade it. It turns grow into a system-wide install rather than a per-user install.
