### ISSUE TITLE
Allow users to add extra functions/tags to Jinja globals object

### ISSUE THREAD

**Issue by WillsB3** [grow/grow#431]
Hi, 

I've been trying to create a custom "tag" akin to the built in `g.static`. However, I'm not sure it's possible with how Grow currently handles extensions.

I've done a little digging with my (very) limited Python skills, and I see that the built-in tags are put onto Jinja's template globals object [here](https://github.com/grow/grow/blob/master/grow/pods/rendered.py#L79), so I assume if a user wants to add their own custom tag they would need to do the same thing. In order to do this though they would need access to the template instance however in order to get this it seems that you would need access to the current view so that it could be passes to `env.get_template` which I don't believe it exposed to the custom extension class.

Are my conclusions correct, and if so is there any scope for more to be exposed to custom extension classes so that custom tags could be implemented?

Many thanks!

**Comment by Zoramite** [comment]
@WillsB3 I'm going to leave this issue as an improvement for extensions to add custom jinja functions/tags. There will probably be some ideas in the image microservice issue that make make this obsolete for your use case, but this is still something that extensions should be able to do.

**Comment by WillsB3** [comment]
@zoramite 👍 - SGTM
