### ISSUE TITLE
Best way to reference internal links in a localized site

### ISSUE THREAD

**Issue by WillDonohoe** [grow/grow#434]
Hi guys,

I have a quick question regarding internal links when building a localized site. There are a few different instances:

* Block copy in content with inline links inside the copy. Unfortunately this leads to HTML inside the content string, which isn't ideal.
eg: 

home.yaml
`body@: Some block copy with <a href="/link/relative/to/root">inline links</a>.`

* Links defined in the content
eg:

home.yaml
```
cta:
  copy@: Cta text
  link: /link/relative/to/root
```

In these cases the links in all languages would be directed to /link/relative/to/root, but what I need is other languages to be directed to the localized path, eg: /intl/locale/link/

I've seen solutions for the second case where they've linked to the yaml file location, and generate a path from inside the view template. However I don't think this would be possible with an inline link like the first example.

Is there any documentation about best practices for dealing with this? Or has anybody come across this before, if so, how did you get around it?

Many thanks,
Will

**Comment by Zoramite** [comment]
The preferred way to link to other internal links is to use the [yaml constructors](http://grow.io/docs/documents/#constructors) in the front matter:

```yaml
# /content/pages/about.yaml
cta:
  copy@: Contact us
  doc: !g.doc /content/page/contact.yaml
```

Then in your view you can do something like this:

```html
<!-- Absolute url -->
<a href="{{cta.doc.url}}">{{cta.copy}}</a>

<!-- Relative url -->
<a href="{{cta.doc.url.path}}">{{cta.copy}}</a>
```

Since you are using a link to the doc it will default to using the same locale as the current document, so you should get a localized url as well.

**Comment by WillDonohoe** [comment]
Hi @Zoramite, thanks for the reply. Yes I saw this documented in a grow example I believe. I don't think this would work for an inline link inside copy though? For example, if I have a block of text with an internal link nested inside:

`copy@: For more information, refer to our <a href="/some/link">documentation</a> pages`

**Comment by Zoramite** [comment]
Here is how you can do it for positional information:

`{{_('Go to %(place)s at %(time)s', place='home', time='3pm')}}`

So you should be able to something like this:

`copy: For more information, refer to our <a href="%(link)">documentation</a> pages`

`{{_(cta.copy, link=cta.doc.url.path)}}`
