### ISSUE TITLE
How to handel preprocessors vendor browser prefix

### ISSUE THREAD

**Issue by syed-haroon** [grow/grow#439]
Can you add something like gulp-autoprefix as default, or there is something already but I am missing?

```
preprocessors:
- kind: sass
```

**Comment by Zoramite** [comment]
Hi @syed-haroon I think the general trend that I have seen with grow projects is to use `gulp` to handle the sass compiling. Specifically for things like this there there is `X` feature not supported that would be good to add would have to be added upstream which would take time to decide to add and then potentially weeks to get deployed to a grow binary.

Instead, by using the gulp preprocessor you are in full control of the configuration of the sass compiler and can add as many of the options and plugins as you want to get the output you are looking for.

**Comment by syed-haroon** [comment]
@Zoramite, thanks for replying. I knew there is this option:
preprocessors:
- kind: gulp

but I was just checking there is something like this, right out of the box:
preprocessors:
- kind: sass
  vendorPerfix: true

something like that, but no problem, I can live with having -kind: gulp :)

I love grow microsite generator, I am using it in many project, it's simple yet powerful :) Thank you.
