### ISSUE TITLE
Broken YAML front matter in HTML documents?

### ISSUE THREAD

**Issue by vitorio** [grow/grow#442]
This used to work, I've a site deploying with grow 0.0.65 where this works.

Using 0.1.6, I appear to be unable to put YAML front matter in an HTML document.  I can't specify $path or $view overrides (the front matter text renders in the document), and if my _blueprint.yaml is empty, the documents don't appear in the collection at all.

**Comment by WillsB3** [comment]
Does your document contain content for multiple locales?

If so there was a breaking change in 0.1.0 that removes support for this in favour of separate localised documents for each locale. 


See the changelog here https://github.com/grow/grow/releases

**Comment by Zoramite** [comment]
Html document formats should be [still supported](https://github.com/grow/grow/blob/master/grow/pods/document_format.py#L42-L43) and the front matter should [still be parsed](https://github.com/grow/grow/blob/master/grow/pods/document_format_test.py#L45-L52).

I'd start with the suggestion from @WillsB3 to run the conversion command: `grow convert --type content_locale_split` and see if that helps with it. If it is still having problems let us know and we can try and track down the issue.

**Comment by vitorio** [comment]
Running that returns the message "Single locale detected, skipping:" for each document, so it wasn't that.

Just ran a fresh test with a virtualenv using an init from the `base` theme, and it worked fine for HTML files saved off the internet... but still not for my documents?

Turns out these old files have **CRLF line endings** (and so my text editor preserved them in my added front matter), and I guess that totally breaks Grow's YAML parser?  I'm not sure why that'd be the case; doesn't Python normalize line endings when you open a file as text?

If you'd like an example, you can unzip [htmlyamltest.zip](https://github.com/grow/grow/files/1066624/htmlyamltest.zip) (two HTML documents and one HTML view) on top of a fresh `base` theme init, `grow run` and visit `http://localhost:8081/_grow`, you should see:

> <Rendered(view='/views/old.html', doc='/content/pages/HTML-MDN.html', locale='en')>
> /mdn

That's the view and path override in the front matter of that document taking effect correctly on an HTML document with `\n` line endings.

About.html also has view and path overridden in the same way, but it shows up incorrectly, as:

> <Rendered(view='/views/base.html', doc='/content/pages/About.html', locale='en')>
> /About/

If you change the line endings in About.html from CRLF to just LF, grow will pick it up correctly.

If you change the line endings in one of the base Markdown content documents to CRLF, you see the front matter in the document text there also.

If you change the line endings in the YAML content document, it continues to work fine.(?!)

(It doesn't look like this is related to #349 but I thought I'd reference it just in case.)

**Comment by Zoramite** [comment]
@vitorio thanks for the in depth work on this bug 👍 

To explain what you were seeing a bit more. The issue was some regex that was used to split the front matter off from the rest of the content. It was pretty explicit on what it would accept as a valid separator line. In this case the extra line ending character made that not match. The same issue would have also affected a document if there were stray space or tab characters at the end and would have been pretty frustrating to debug.

For yaml documents working with either line endings: yaml documents cannot be 'split' with other content, the entire document is front matter. So it completely bypasses the logic for splitting the raw document content.
