### ISSUE TITLE
Add an environment/deployment flag to grow run

### ISSUE THREAD

**Issue by uxder** [grow/grow#444]
I would like to be able to pass environment variables via the` grow run` command.

Given something like: 

` grow run --env=debug`

I want to be able access that in my templates to show content only if that flag is passed:

```
{% if env.name == 'debug' %}
   <div>Shown only for enviroment debug<div>
{% endif %}
```

This could also be tied to deployments in podspec.yaml.

` grow run --deployment=growsdk`

**Comment by Zoramite** [comment]
That is a great idea. The flag should specify the deployment configuration to run instead of arbitrary environment variables.
