### ISSUE TITLE
Evaluate and add support for post processors

### ISSUE THREAD

**Issue by jeremydw** [grow/grow#51]
- Develop support for post processors (processing that happens after resources are built).
- A good candidate may be Tidy for HTML5 documents: https://github.com/w3c/tidy-html5

**Comment by willthomson** [comment]
We'd love to see this feature implemented, particularly for Tidy. Any plans to implement soon?

**Comment by matthewhall** [comment]
+1 to this. Would be very useful.

**Comment by WillsB3** [comment]
I've started to see developers using frivolous amounts of comments in the source templates just to ensure that the output HTML contains no newlines/extra whitespace.

These comments make the template harder to read, and harder to modify.

Have you had any more thoughts on post-processors, specifically some form of HTML Tidy implementation ...?

**Comment by kezlya** [comment]
For compressing HTML we can use [jinja2htmlcompress](https://github.com/mitsuhiko/jinja2-htmlcompress) extention created by @mitsuhiko . Place `jinja2htmlcompress.py` file to the `extensions` folder and modify your `podspec.yaml` file
```
extensions:
    jinja2:
        - extensions.jinja2htmlcompress.HTMLCompress
```
You can also use `SelectiveHTMLCompress`
It's pretty fast and not adds much overhead

_I'm adding a "Pretty Print" option_

**Comment by stueja** [comment]
@kezlya , as me being a noob in Python and grow.io -- where is 

> the `extensions` folder

?
Is that 
 - an extensions folder anywhere below one of the many Python directories
 - an extensions folder in ~/bin/grow
 - an extensions folder in my current grow pod?

Thanks alot,
Jan

**Comment by WillsB3** [comment]
Add the extensions folder (the name is not actually important) to the root
of your pod. You'll then need to update your podspec to enable
any extension you've added. See the docs here for further details
https://grow.io/docs/extensions/.

**Comment by stueja** [comment]
Ups, I really skipped that part of the documentation :/ Thanks alot!

**Comment by derekcecillewis** [comment]
Is anyone working on this? I'd love to collaborate.

**Comment by Zoramite** [comment]
This is now available when using the `--re-route` flag. See an [html min example extension](https://github.com/grow/grow-ext-html-min).
