### ISSUE TITLE
Travis build is stalled and no output produced when using grow 0.2.3

### ISSUE THREAD

**Issue by bpaduch** [grow/grow#512]
Production build using Grow 0.2.3 in Travis CI fails with the following error: "**No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself**." The actual "building" doesn't kick off.  

Production build: https://travis-ci.org/ampproject/docs/builds/267810002

I set the build to grow version to 0.2.2 and Travis build [succeeds](https://travis-ci.org/ampproject/docs/builds/268049693).

**Comment by molavec** [comment]
Any work around to solve it?

**Comment by bpaduch** [comment]
I reverted to the old version - 0.2.2

**Comment by Zoramite** [comment]
Does it work locally for you with the version `0.2.3`? I've tried it out locally and it is building correctly, so I am trying to figure out a good way to reproduce.

**Comment by molavec** [comment]
I'm using mac OS sierra 10.12.5 

I just follow codelab tutorial and I getting this:

     cd /tmp
     angel ❯ grow init codelab ./my-codelab/
     
     Initializing with https://github.com/growthemes/     codelab.git...
     Pod ready to go: /private/tmp/my-codelab
     angel ❯ grow build ./my-codelab
     [15:46:02] Compiled: de (33/33)
     [15:46:02] Compiled: /source/sass/main.scss -> /dist/main.min.css
     Building: 42/42 (in 0.459008)                                                                
     Traceback (most recent call last):
       File "grow", line 92, in <module>
       File "click/core.py", line 722, in __call__
       File "click/core.py", line 697, in main
       File "click/core.py", line 1066, in invoke
       File "click/core.py", line 895, in invoke
       File "click/core.py", line 535, in invoke
       File "grow/commands/build.py", line 41, in build
       File "grow/deployments/destinations/base.py", line 249, in dump
       File "grow/pods/pods.py", line 242, in dump
       File "grow/pods/pods.py", line 271, in export
       File "grow/pods/rendered.py", line 71, in render
       File "grow/templates/doc_dependency.py", line 10, in __init__
     AttributeError: 'NoneType' object has no attribute 'pod'
     Failed to execute script grow

**Comment by Zoramite** [comment]
@molavec That should be fixed with this commit, which will be part of the next release: https://github.com/grow/grow/commit/5cd3ddae24fdfe9e0593085e583476dd36c7a75a

**Comment by molavec** [comment]
Thanks! I will try it.

**Comment by bpaduch** [comment]
I'm able to build successfully locally, however, it takes a long time.

**Comment by pbakaus** [comment]
Ugh! Was already wondering about the Travis build errors, glad you catched it.. hope a solution is found soon.

**Comment by Zoramite** [comment]
I removed a progress bar change that may have been affecting things in 70e7b7ec82dd78cab4c2160148471e8f7df24249 .

I'm going to try another release tomorrow and we'll see if it works without the progress bar changes. Otherwise I'll have to try and dig deeper into what would cause that to fail.

**Comment by Zoramite** [comment]
I've released the `0.2.4` tag if you could try it out with your build and see if it still hangs or has other issues.

**Comment by bpaduch** [comment]
[Master built successfully](https://travis-ci.org/ampproject/docs/builds/268342191) with 0.2.4; building production now.

FYI, the countdown is still present:
![build-countdown](https://user-images.githubusercontent.com/1012254/29714499-8079ddbc-8971-11e7-96a2-183b56f4792f.png)

**Comment by bpaduch** [comment]
Works. :)

**Comment by Zoramite** [comment]
Great, Thanks!

**Comment by Zoramite** [comment]
@bpaduch The change that was breaking was to replace the normal progress bar with one that was dumbed down so it didn't fill up the logs. But it appears to have an issue.

For the pip install, if you don't specify a version it will do the latest version.
