### ISSUE TITLE
Google Sheets `format_as: strings` enhancements

### ISSUE THREAD

**Issue by jeremydw** [grow/grow#522]
### 1 - Auto-create keys

One feature request for the `format_as: strings` option for Google Sheets - we should automatically allocate IDs if there is a string present, but no key. For example, this can make it possible to more rapidly prototype or rapidly send a translation request without being blocked by string ID creation.

Here's what our strings should ideally look like:
![image](https://user-images.githubusercontent.com/646525/29796649-36374c6a-8c07-11e7-9c2c-ffe3c829f7ae.png)

But here's what they will look like prior to creating an ID:
![image](https://user-images.githubusercontent.com/646525/29796672-5266942c-8c07-11e7-9058-9f918e9b90ec.png)

We can auto create IDs (in this example, `key`s) for strings that are missing them. My suggestion would probably be to just use a number based on the row if the first column is empty - or if there are only Thoughts?

E.g.:
```
1: Hello World!
2: Say hello to the world.
```

### 2 - Exclude empty strings

If a row has a key but no value, exclude the value from being added to the sheet.

**Comment by Zoramite** [comment]
I could see that it would help with creating translation requests before they are in use. We could do something like `_untranslated_2` for the keys. The feature would definitely be off by default.

Other than translations, how does it make prototyping faster? If you are taking the time to use a string you should be taking the time to properly name the key shouldn't you?

**Comment by jeremydw** [comment]
Yeah, this would primarily be for rapidly filing translation requests. I agree - using the string itself should probably require the developer to allocate a human-created ID.
