### ISSUE TITLE
I'm trying to install grow but I am getting this error

### ISSUE THREAD

**Issue by ionutindreica** [grow/grow#536]
curl https://install.growsdk.org | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   377  100   377    0     0   1861      0 --:--:-- --:--:-- --:--:--  1866
  File "/tmp/tmp.W3ZNMXQxY0/install_growsdk.py", line 36
    print text.format(*args, **{
             ^
SyntaxError: invalid syntax

Does anyone experienced this kind of error?

**Comment by jeremydw** [comment]
Which system are you using? Grow currently supports Mac/Linux + Python2.7 without modification.

You could also try installing with `pip install grow`.

**Comment by ionutindreica** [comment]
Ubuntu 16.04 LTS

**Comment by ionutindreica** [comment]
I have just installed the Ubuntu and and latest version of python.

**Comment by Zoramite** [comment]
Sounds like you are using python 3. Can you double check the python version
being used?

**Comment by ionutindreica** [comment]
It's 3.5.2 I believe. I'm not in front of my pc now.

**Comment by ionutindreica** [comment]
Finally I have manged to install grow 
when I runt grow init base  base
grow run    after 

I have this  warning Warning: libyaml missing, using slower yaml parser.
Is it normal or what should I do or how to fix it?
Thank you

**Comment by ionutindreica** [comment]
Can you please tell me how to install libyaml   to solve this warning?

I've been installed this in the project folder:  `sudo apt-get install libyaml-dev` 
`pip install --user PyYAML` 

after I run grow again I still have this warning.

Please help fix this.

Thank you

**Comment by Zoramite** [comment]
You can try it with this command: `pip install --upgrade --force-reinstall pyyaml` I believe that it has to be specifically forced to recompile the pyyaml to use the installed libyaml.

**Comment by ionutindreica** [comment]
Thank you @Zoramite I have run that command and still getting that error.
I do not know what else to do. I've been google it a lot and still not come to an end.

**Comment by Zoramite** [comment]
Well, when we are developing grow we use these commands in the makefile to get things setup: https://github.com/grow/grow/blob/master/Makefile#L59-L73

I'm not sure right off what else to try if that is not helping with the libyaml installation. Everything will also still work, just won't be as fast as with the libyaml parser.
