### ISSUE TITLE
Using g.yaml with a file that doesn't exist or misformatting a yaml document throws grow into a error state

### ISSUE THREAD

**Issue by jeremydw** [grow/grow#543]
You can throw the development server into a stuck error state with the following:

```
foo: !g.yaml /content/to/bad/file.yaml
```

or by making a sytax error in a yaml file.

Either issue requires a restart of Grow to fix it. We should catch YAML parsing errors, bubble them up (as we do now), and allow users to fix YAML without a restart.

**Comment by Zoramite** [comment]
I don't think this is still an issue, but if it is we can reopen it.
