### ISSUE TITLE
metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

### ISSUE THREAD

**Issue by ViktorZharina** [grow/grow#546]
update grow to 0.2.8

OS
Distributor ID:	LinuxMint
Description:	Linux Mint 18.1 Serena
Release:	18.1

Python 2.7.12

Got error about pyOpenssl, then upgrade it sudo pip install -U pyopenssl

then `grow run`  and

Warning: libyaml missing, using slower yaml parser.
Traceback (most recent call last):
  File "/usr/local/bin/grow", line 42, in <module>
    from grow.common import ca_certs_locater
  File "/usr/local/lib/python2.7/dist-packages/grow/__init__.py", line 12, in <module>
    from .pods.pods import Pod
  File "/usr/local/lib/python2.7/dist-packages/grow/pods/pods.py", line 19, in <module>
    from grow.preprocessors import preprocessors
  File "/usr/local/lib/python2.7/dist-packages/grow/preprocessors/preprocessors.py", line 1, in <module>
    from . import blogger
  File "/usr/local/lib/python2.7/dist-packages/grow/preprocessors/blogger.py", line 6, in <module>
    from protorpc import messages
  File "/usr/local/lib/python2.7/dist-packages/protorpc/messages.py", line 1146, in <module>
    class Field(six.with_metaclass(_FieldMeta, object)):
TypeError: Error when calling the metaclass bases
    metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

Thank you.

**Comment by ViktorZharina** [comment]
Fast fix
protorpc/messages.py:1155
-__metaclass__ = _FieldMeta
+#__metaclass__ = _FieldMeta

**Comment by stevenle** [comment]
I started getting this issue on CI as well. Not sure what changed.

**Comment by stevenle** [comment]
I switched my CI to use the `grow/baseimage` docker image and things seem to be working better now. The above error might still be happening with versions of grow that are `pip install`ed. I was able to work around the issue in another project by having something like the following in my `requirements.txt`:

```
grow==0.2.8
protorpc==0.10.0
```

Then `pip install -r requirements.txt` seemed to work. Not really sure what changed, since the logs in the last successful build used `protorpc==0.11.1`.

**Comment by bpaduch** [comment]
Experiencing same issue (https://travis-ci.org/ampproject/docs/builds/276831477); don't really want to add new file.  Any other workaround or fix?

**Comment by Zoramite** [comment]
@bpaduch does it help to rebuild without cache? I see that an [earlier build](https://travis-ci.org/ampproject/docs/builds/276399033) also used `0.2.8` and didn't have any issues with the build. Is there something else that is different between those two builds?

**Comment by bpaduch** [comment]
@Zoramite - I emptied the cache and retried the [build](https://travis-ci.org/ampproject/docs/builds/276926625) but same issue.  Gonna downgrade version and see what happens.

**Comment by stevenle** [comment]
Happening across multiple machines so I doubt it's related to cache. Possibly something changed on the pip side. @Zoramite a quick fix might be to pin grow's protorpc dep to 0.10.0.

**Comment by Zoramite** [comment]
@stevenle Grow has been using [protorpc 0.11.1](https://github.com/grow/grow/commit/138e4c04c6a9e53223fe9be09e68cd5d796ba86a) for over a year, so I don't think that it is directly a problem with the protorpc version.

**Comment by stevenle** [comment]
possibly an issue with `six` in that case, i'm seeing a few recent commits related to metaclass in the past day or so:

https://github.com/benjaminp/six/commits/master

might want to pin to a specific version of six.

**Comment by bpaduch** [comment]
Agreed - it's the only difference.

**Comment by Zoramite** [comment]
Six does seem to be having issues: https://github.com/benjaminp/six/issues/210

**Comment by pbakaus** [comment]
Is there any short term workaround we can do on our own until a new version with the hotfix for grow is deployed on pip?

**Comment by Zoramite** [comment]
I just released `0.2.9` on pip which hopefully fixes it with the frozen dep.

**Comment by pbakaus** [comment]
Thanks a ton @Zoramite, seems to have done the job!
