### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by ionutindreica** [grow/grow#557]
I have this message after I run `grow` or `grow build` command.
I've been struggling whit this error for couple of days.
I have deleted everything reinstall the system, rebuild virtual environment and it is still there every time.

How can I solve this?
I'm trying to use your tool whit amppproject, so if you could guide me how to fix it that would be great.

Thank you,
John

**Comment by ionutindreica** [comment]
(ldc) john@john-dev-ub16:~/developer/ldc$ grow build
Segmentation fault (core dumped)
(ldc) john@john-dev-ub16:~/developer/ldc$ journalctl -e
sep 21 15:09:08 john-dev-ub16 sudo[7648]: pam_unix(sudo:session): session opened
sep 21 15:09:08 john-dev-ub16 sudo[7648]: pam_unix(sudo:session): session closed
sep 21 15:17:01 john-dev-ub16 CRON[8023]: pam_unix(cron:session): session opened
sep 21 15:17:01 john-dev-ub16 CRON[8024]: (root) CMD (   cd / && run-parts --rep
sep 21 15:17:01 john-dev-ub16 CRON[8023]: pam_unix(cron:session): session closed
sep 21 15:23:40 john-dev-ub16 sudo[8314]:     john : TTY=pts/1 ; PWD=/home/john 
sep 21 15:23:40 john-dev-ub16 sudo[8314]: pam_unix(sudo:session): session opened
sep 21 15:23:41 john-dev-ub16 sudo[8314]: pam_unix(sudo:session): session closed
sep 21 15:26:13 john-dev-ub16 sudo[8439]:     john : TTY=pts/1 ; PWD=/home/john 
sep 21 15:26:13 john-dev-ub16 sudo[8439]: pam_unix(sudo:session): session opened
sep 21 15:26:20 john-dev-ub16 sudo[8439]: pam_unix(sudo:session): session closed
sep 21 15:26:26 john-dev-ub16 sudo[8732]:     john : TTY=pts/1 ; PWD=/home/john 
sep 21 15:26:26 john-dev-ub16 sudo[8732]: pam_unix(sudo:session): session opened
sep 21 15:26:32 john-dev-ub16 sudo[8732]: pam_unix(sudo:session): session closed
sep 21 15:26:36 john-dev-ub16 sudo[9176]:     john : TTY=pts/1 ; PWD=/home/john 
sep 21 15:26:36 john-dev-ub16 sudo[9176]: pam_unix(sudo:session): session opened
sep 21 15:26:49 john-dev-ub16 sudo[9176]: pam_unix(sudo:session): session closed
sep 21 15:29:58 john-dev-ub16 kernel: show_signal_msg: 13 callbacks suppressed
sep 21 15:29:58 john-dev-ub16 kernel: grow[10742]: segfault at 0 ip 00007f5f8bd2
sep 21 15:32:32 john-dev-ub16 org.gnome.zeitgeist.SimpleIndexer[1840]: ** (zeitg
sep 21 15:32:54 john-dev-ub16 kernel: grow[10823]: segfault at 0 ip 00007fb24496
sep 21 15:44:05 john-dev-ub16 gnome-session[1967]: ** (zeitgeist-datahub:2275): 
sep 21 15:44:05 john-dev-ub16 gnome-session[1967]: ** (zeitgeist-datahub:2275): 
lines 979-1001/1001 (END)
sep 21 15:09:08 john-dev-ub16 sudo[7648]: pam_unix(sudo:session): session opened for user root by (uid=0)
sep 21 15:09:08 john-dev-ub16 sudo[7648]: pam_unix(sudo:session): session closed for user root
sep 21 15:17:01 john-dev-ub16 CRON[8023]: pam_unix(cron:session): session opened for user root by (uid=0)
sep 21 15:17:01 john-dev-ub16 CRON[8024]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
sep 21 15:17:01 john-dev-ub16 CRON[8023]: pam_unix(cron:session): session closed for user root
sep 21 15:23:40 john-dev-ub16 sudo[8314]:     john : TTY=pts/1 ; PWD=/home/john ; USER=root ; COMMAND=/usr/bin/apt-get install git
sep 21 15:23:40 john-dev-ub16 sudo[8314]: pam_unix(sudo:session): session opened for user root by (uid=0)
sep 21 15:23:41 john-dev-ub16 sudo[8314]: pam_unix(sudo:session): session closed for user root
sep 21 15:26:13 john-dev-ub16 sudo[8439]:     john : TTY=pts/1 ; PWD=/home/john ; USER=root ; COMMAND=/usr/bin/apt-get update
sep 21 15:26:13 john-dev-ub16 sudo[8439]: pam_unix(sudo:session): session opened for user root by (uid=0)
sep 21 15:26:20 john-dev-ub16 sudo[8439]: pam_unix(sudo:session): session closed for user root
sep 21 15:26:26 john-dev-ub16 sudo[8732]:     john : TTY=pts/1 ; PWD=/home/john ; USER=root ; COMMAND=/usr/bin/apt-get install nodejs
sep 21 15:26:26 john-dev-ub16 sudo[8732]: pam_unix(sudo:session): session opened for user root by (uid=0)
sep 21 15:26:32 john-dev-ub16 sudo[8732]: pam_unix(sudo:session): session closed for user root
sep 21 15:26:36 john-dev-ub16 sudo[9176]:     john : TTY=pts/1 ; PWD=/home/john ; USER=root ; COMMAND=/usr/bin/apt-get install npm
sep 21 15:26:36 john-dev-ub16 sudo[9176]: pam_unix(sudo:session): session opened for user root by (uid=0)
sep 21 15:26:49 john-dev-ub16 sudo[9176]: pam_unix(sudo:session): session closed for user root
sep 21 15:29:58 john-dev-ub16 kernel: show_signal_msg: 13 callbacks suppressed
sep 21 15:29:58 john-dev-ub16 kernel: grow[10742]: segfault at 0 ip 00007f5f8bd25746 sp 00007fff190163c8 error 4 in libc-2.23.so[7f5f8bc9a000+1c0000]
sep 21 15:32:32 john-dev-ub16 org.gnome.zeitgeist.SimpleIndexer[1840]: ** (zeitgeist-fts:2295): WARNING **: Unable to get info on application://nautilus-autostart.desktop
sep 21 15:32:54 john-dev-ub16 kernel: grow[10823]: segfault at 0 ip 00007fb24496f746 sp 00007ffcf2f3d488 error 4 in libc-2.23.so[7fb2448e4000+1c0000]
sep 21 15:44:05 john-dev-ub16 gnome-session[1967]: ** (zeitgeist-datahub:2275): WARNING **: zeitgeist-datahub.vala:212: Error during inserting events: GDBus.Error:org.gnome.zeitg
sep 21 15:44:05 john-dev-ub16 gnome-session[1967]: ** (zeitgeist-datahub:2275): WARNING **: zeitgeist-datahub.vala:212: Error during inserting events: GDBus.Error:org.gnome.zeitg

(ldc) john@john-dev-ub16:~/developer/ldc$

**Comment by tuanluu-agilityio** [comment]
Hi @ionutindreica ,

I'm not sure, but you can try with command `sudo grow build` or `sudo grow`.
I have same error when I run command `grow run` and fix it with command `sudo grow run`.

Thanks,

**Comment by jeremydw** [comment]
Does this happen if you install grow via `pip install grow` rather than the pre-built version we distribute? Can you try installing with `pip install grow` and report back?

**Comment by NetLancer** [comment]
Amazingly it is still the same - "Segmentation fault (core dumped)" with my installation on ubuntu (based) linux.
Even after pip install, grow command outputs just the line above (http://lxle.net/  OS)
