### ISSUE TITLE
Optimize memory usage in grow deploys

### ISSUE THREAD

**Issue by stevenle** [grow/grow#576]
Grow stage and deploy, afaik, renders all files and stores the rendered contents in memory before "deploying" to its target. For very large sites, this can cause memory issues.

Not sure what the best implementation is, but a suggestion is to write out the contents to some tmp folder before deploying.

Also, possibly related: can you double-check to make sure file descriptors are being closed after `pod.open_file()`?

**Comment by stevenle** [comment]
I was monitoring the memory usage and file descriptor count during a grow stage and noticed the fd count went from ~2.8K to ~8.9K after the build finished and was starting to deploy to webreview. After the grow process crashed, the fd count went to about 1.2K.

<img width="697" alt="screen shot 2017-09-29 at 4 26 18 pm" src="https://user-images.githubusercontent.com/387282/31039509-ff8380a4-a532-11e7-8e1f-1647c25c1628.png">

<img width="89" alt="screen shot 2017-09-29 at 4 26 31 pm" src="https://user-images.githubusercontent.com/387282/31039511-0352d87e-a533-11e7-8052-699b624a3a2b.png">

**Comment by Zoramite** [comment]
We added some better memory usage by using temp files to write the rendered content to while in flight instead of just storing everything in memory. This seems to make the memory a lot more efficient.

Fixed by #579
