### ISSUE TITLE
Using Service Workers (PWA) with Grow

### ISSUE THREAD

**Issue by Quirksmode** [grow/grow#604]
Hi, I have been using the Grow framework for a few weeks now and have been really impressed. One thing I am struggling with is converting the site to a PWA.

The issue I have is that because I am using the fingerprint functionality for my CSS, JS and Images, (which generates fingerprinted file names) I am then unable to target these files from within JS files (service-worker.js). I need to be able to pass to the JS file what the fingerprint and root path will be.

One idea I had was to create a global JS object and pass the variables to the service-worker.js file

e.g. within base.html

let APP = {}
APP.fingerprint = {{env.fingerprint}}
APP.root = {{podspec.root}}

The problem I have is that the env.fingerprint variable does not seem to match fingerprint on the built files.

How can I assign the correct fingerprint variables so I can set the correct paths for the files in the service-worker.js file?

e.g.

const installFilesEssential = [
root + 'static/js/main-' + fingerprint + '.min.js',
root + 'static/css/main-' + fingerprint + '.css',
]

Does this technique seem ok, or is there a better way?

**Comment by Zoramite** [comment]
Try `{{g.static('/path/to/js/file.js').url.path}}` That should give you the correct file names.

For example if you build your js files to `/dist/`:

```
const installFilesEssential = [
'{{g.static('/dist/js/main.min.js').url.path}}',
'{{g.static('/dist/css/main.min.css').url.path}}',
]
```

**Comment by Quirksmode** [comment]
Hi,

Thanks for getting back to me. Sadly I am unable to pass in {{}} variables
in this way with Javascript files, it copies the file to the build folder,
but it doesn't parse the variables and just outputs:

const installFilesEssential = [
'{{g.static('/dist/js/main.min.js').url.path}}',
'{{g.static('/dist/css/main.min.css').url.path}}',
]


Is there an option I am missing to allow this?


Additionally, setting the paths will not be enough, I need to pass in
a unique identifier to clear the Service Worker cache in case files
get updated. How can I grab the unique fingerprint as a variable to
use in my code? env.fingerprint outputs a code, but it does not update
each time like the filenames do, it's strange that they do not match?


Thanks,


Dave

**Comment by Zoramite** [comment]
Sorry, I was meaning in the base.html you could do it as a variable your scripts could use. The paths will have the fingerprint when it is built or you can do `{{g.static('/dist/js/main.min.js').fingerprint}}` to get the value of the fingerprint directly.

**Comment by jeremydw** [comment]
Hello @Quirksmode - thanks for the question. @Zoramite is correct, and I just wanted to offer one additional point of clarity:

- `{{env.fingerprint}}` is a fingerprint related to the build environment (i.e. the build timestamp)
- There is an additional `fingerprint` property of a `StaticFile` object that is a hash of the file's contents. I'd advise using this fingerprint via something like @Zoramite's example.

A complete example in your HTML file might be:

```
window.PATHS = {
    main: {{g.static('/dist/js/main.min.js').fingerprint}},
    foo: {{g.static('/dist/js/foo.min.js').fingerprint}}
};
```

And then access from your JavaScript:

```
window.PATHS.main
```

etc.
