### ISSUE TITLE
Move away from keyring

### ISSUE THREAD

**Issue by stevenle** [grow/grow#610]
The latest versions of Ubuntu has issues with `python-keyring` on a fresh install. When using anything that requires an oauth token, you get:

```
No recommended backend was available. Install the keyrings.alt package if you want to use the non-recommended backends. See README.rst for details.
```

**Comment by Zoramite** [comment]
What is the suggested replacement? I'm assuming we could update the oauth libraries at the same time. I think we had some issues with upgrading before, maybe from the keyring support?

**Comment by stevenle** [comment]
Apparently oauth2client is being deprecated (which I think is a good thing). "We recommend you use google-auth and oauthlib. For more details on the deprecation, see oauth2client deprecation."

https://github.com/google/oauth2client

I haven't looked too closely at [google-auth](https://google-auth.readthedocs.io/en/latest/) yet but it looks like it might handle token storage by default depending on your platform.

**Comment by Zoramite** [comment]
I don't remember which release, but it looks like we don't use keyring anymore, so I'm going to close this issue.
