### ISSUE TITLE
Default ordering of g.docs()

### ISSUE THREAD

**Issue by stevenle** [grow/grow#612]
I noticed that the returned docs from `g.docs(<collection>)` returns a list of documents in reverse alphabetical order by filename. Doesn't it make more sense to use alphabetical ordering?

**Comment by Zoramite** [comment]
The default ordering for `g.docs` is actually the `$order` of the document... which for most docs is nothing. There really isn't a secondary sorting ability currently.

**Comment by stevenle** [comment]
I guess what I'm saying is that the default ordering at the moment doesn't make much sense. Like, if all the docs in a collection don't have any `$order` specified, there should be some relatively sane default ordering returned, right? At the moment it appears to be reverse alphabetically sorted which doesn't make much sense to me.

But even if some docs have an `$order` set while others don't, we should expect some sane ordering there too. Like, sort documents that have a specific `$order` first, then afterwards, order by some default.

**Comment by Zoramite** [comment]
Yeah, I think that is a sane thing to do... Just need to figure out how to do a more complicated sort so that we can default it to a secondary sort attribute.

**Comment by Zoramite** [comment]
NM, turns out python is pretty cool. Added a secondary sort order by the `pod_path`.

**Comment by Zoramite** [comment]
Also, just expended it out so that you can use something like `order_by='title'` or `order_by=('order', 'title')` to provide any set of attribute sorting.
