### ISSUE TITLE
Grow Build doesn't build all files

### ISSUE THREAD

**Issue by bpaduch** [grow/grow#629]
When performing `grow build`, only a portion of the files are actually built (155 out of 4637). Even though the console message says all files built and deployed.

Started with version 3.10.  Doesn't happen with 3.9.

When I downgrade to 3.9, it works as expected.

## Steps to reproduce

1. Run `grow build` on https://github.com/ampproject/docs.
2. In the "build" folder, on the "examples" folder and contents is present.  Expected over 4000 files.

**Comment by Zoramite** [comment]
This is fixed in `0.3.11` but you will probably need to delete the `build/` directory since the index that it uses for comparison thinks that the files are there.
