### ISSUE TITLE
Allow ordering by the dates field.

### ISSUE THREAD

**Issue by Zoramite** [grow/grow#634]
Currently there is no built-in way to sort documents by the `$dates` field.

Would be good to be able to do a `{{g.docs('posts', order_by='dates.published')}}` to sort the documents.

**Comment by jeremydw** [comment]
Does the following work? After discovering the flexibility of Jinja's built in `sort` filter I wonder how much custom code we should add to the `order_by` kwarg.

```
{{g.docs('posts')|sort(attribute='dates.published')}}
```

**Comment by j9t** [comment]
If this is related to the original request, no, I had tried that before, in different combinations. When I just added it to respective template Grow everything blows up with

`BuildError: Error building <Rendered(view='/views/index.html', doc='/content/pages/index.md', locale='de')>: 'instancemethod object' has no attribute 'published'`

**Comment by Zoramite** [comment]
I found the project that I originally added the `dates` functionality for. I was doing this to get the the latest 4 posts:

`{% set posts = g.docs('posts', order_by='date')[-4:] | reverse() %}`

I was using the `$date: 2008-05-28` instead of using `$dates` to do the ordering. I guess it depends on how much you need to have multiple dates in a post. If you really want to manually track when it was created, last edited, etc then it makes the `$dates` more important. But if you want to be able to easily sort then just using `$date` is actually easier and works with the default ordering/sorting.

**Comment by j9t** [comment]
That works (thanks!). When you mentioned `#dates` I noticed how I had just taken that from the Grow examples. I switched everything to `$date` which hopefully will suffice.
