### ISSUE TITLE
# of files created different b/w master and production

### ISSUE THREAD

**Issue by bpaduch** [grow/grow#636]
With Grow 3.11, the number of files actually in the "build" folder differ when building Master vs. Production, even though both branches have the same code!  This was working correctly with 3.9, that is, the number of files in Master's build folder = Production's build folder.  Missing approximately 24 files. As a result, missing files = 404's to docs.  We've reverted back to Grow 3.9.

## Steps to reproduce:

  Using [AMP's docs](https://github.com/ampproject/docs).

Note: I delete the build folder beforehand to ensure starting from fresh.

1. Run `grow build` with **master branch**.  Count files in build folder.  
2. Run `grow build` with **production** branch.  Count files in build folder.
3. Files in master's build folder != Files in production build folder.
4. Revert to Grow 3.9.
5. Run `grow build` with **master** branch.
6. Run `grow build` with **production** branch.  Count files build folder.
7. Files in master's build folder = Files in production build folder.

## Expected

`#` of files in Master's build folder = `#` of files in Production's build folder

## Version
Grow 3.11

cc: @pbakaus

**Comment by Zoramite** [comment]
I'm showing different files between master and production...? Is that correct?

```sh
Randy:amp-project-docs randy$ git checkout production
M	assets/img/sprite.svg
M	content/includes/list-blog-ads.yaml
M	content/includes/list-blog.yaml
M	content/includes/tweets.yaml
M	content/latest/blog-ads/ads-amp-roadmap-update-for-end-of-q2.md
M	content/latest/blog-ads/ads-e-commerce-at-the-speed-of-amp.md
M	content/latest/blog-ads/ads-even-faster-loading-ads-in-amp.md
M	content/latest/blog-ads/ads-faster-amp-ad-landing-page-support-from-adwords.md
M	content/latest/blog-ads/ads-introducing-the-amp-roadshow-bringing-the-amp-team-to-you.md
M	content/latest/blog-ads/ads-new-in-amp-position-observers-fluid-ads-and-improved-analytics-for-video-beyond.md
M	content/latest/blog-ads/ads-putting-the-amp-in-progressive-web-amps-meet-the-shadowreader.md
M	content/latest/blog-ads/ads-the-argument-for-amp-lessons-from-10-case-studies.md
M	content/latest/blog-ads/ads-the-why-and-how-of-accelerated-mobile-pages-at-conde-nast.md
M	content/latest/blog/e-commerce-at-the-speed-of-amp.md
M	content/latest/blog/even-faster-loading-ads-in-amp.md
M	content/latest/blog/faster-amp-ad-landing-page-support-from-adwords.md
M	content/latest/blog/introducing-the-amp-roadshow-bringing-the-amp-team-to-you.md
M	content/latest/blog/new-in-amp-position-observers-fluid-ads-and-improved-analytics-for-video-beyond.md
M	content/latest/blog/putting-the-amp-in-progressive-web-amps-meet-the-shadowreader.md
M	content/latest/blog/start-fast-with-new-amp-start-templates.md
M	content/latest/blog/the-argument-for-amp-lessons-from-10-case-studies.md
M	content/latest/blog/the-why-and-how-of-accelerated-mobile-pages-at-conde-nast.md
```

**Comment by Zoramite** [comment]
Actually it seems that the preprocessing is changing the content. I reverted all the changes and there is indeed no diff between master and productions. But when I run the preprocessing:

```sh
$ grow preprocess
...
$ git status
On branch production
Your branch is up-to-date with 'origin/production'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   assets/img/sprite.svg
	modified:   content/includes/list-blog-ads.yaml
	modified:   content/includes/list-blog.yaml
	modified:   content/includes/tweets.yaml
	modified:   content/latest/blog-ads/ads-amp-roadmap-update-for-end-of-q2.md
	modified:   content/latest/blog-ads/ads-e-commerce-at-the-speed-of-amp.md
	modified:   content/latest/blog-ads/ads-even-faster-loading-ads-in-amp.md
	modified:   content/latest/blog-ads/ads-faster-amp-ad-landing-page-support-from-adwords.md
	modified:   content/latest/blog-ads/ads-introducing-the-amp-roadshow-bringing-the-amp-team-to-you.md
	modified:   content/latest/blog-ads/ads-new-in-amp-position-observers-fluid-ads-and-improved-analytics-for-video-beyond.md
	modified:   content/latest/blog-ads/ads-putting-the-amp-in-progressive-web-amps-meet-the-shadowreader.md
	modified:   content/latest/blog-ads/ads-the-argument-for-amp-lessons-from-10-case-studies.md
	modified:   content/latest/blog/e-commerce-at-the-speed-of-amp.md
	modified:   content/latest/blog/even-faster-loading-ads-in-amp.md
	modified:   content/latest/blog/faster-amp-ad-landing-page-support-from-adwords.md
	modified:   content/latest/blog/introducing-the-amp-roadshow-bringing-the-amp-team-to-you.md
	modified:   content/latest/blog/new-in-amp-position-observers-fluid-ads-and-improved-analytics-for-video-beyond.md
	modified:   content/latest/blog/putting-the-amp-in-progressive-web-amps-meet-the-shadowreader.md
	modified:   content/latest/blog/start-fast-with-new-amp-start-templates.md
	modified:   content/latest/blog/the-argument-for-amp-lessons-from-10-case-studies.md
	modified:   content/latest/blog/the-why-and-how-of-accelerated-mobile-pages-at-conde-nast.md

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	content/latest/blog-ads/ads-amp-two-years-of-user-first-webpages.md
	content/latest/blog/amp-two-years-of-user-first-webpages.md
```

**Comment by bpaduch** [comment]
Those files are expected to be modified - they get built during the process, and happens for both master and production.  When you dig into the directories, like the "docs" directory, files are missing.  Is that because of the preprocessor?  Did it change in 3.11?

**Comment by Zoramite** [comment]
I am running the build for `production` to do a diff right now, I'll let you know when I get more information.

**Comment by Zoramite** [comment]
QQ: Did you use `0.3.10` at all? There was a bug in that release that caused some issues. Can you try upgrading to `0.3.11`, delete the `build/` directory and then try again and see if you notice any difference between the two builds?

I am trying to reproduce it and I haven't been able to see the changes that you are seeing with a fresh build.

**Comment by bpaduch** [comment]
Yes, tried 3.10 before and I reported the issue that the build wasn't be created correctly (see [629](https://github.com/grow/grow/issues/629)).

I just again did a 3.11 build against master, and against production, again same results as I reported.

**Comment by Zoramite** [comment]
I was able to reproduce this bug by running the build multiple times with different output directories. It seems there is some bug with how I updated the deploy step to copy files instead of read/write each one.

Reverting that change seems to go back to consistent results with the repeated builds.
