### ISSUE TITLE
Create /_grow/ admin console on the development server

### ISSUE THREAD

**Issue by jeremydw** [grow/grow#67]
Users should be able to kick off preprocessors or run commands like `machine_translate` through a web-based admin console. Particularly useful for Google Sheets integration to manually trigger a redownload without restarting the dev server.

**Comment by jeremydw** [comment]
The admin console could also have a simple view that shows all the routes in the pod (similar to `grow routes` command).

**Comment by Zoramite** [comment]
Closing since we have a rudimentary admin. Tracking future features of the console in https://github.com/grow/grow/projects/5
