### ISSUE TITLE
Grow 3.17: Git is not available in this environment (Linux)

### ISSUE THREAD

**Issue by bpaduch** [grow/grow#675]
When running "grow build" with the packaged grow 3.17  for Linux, I get the following error: 

grow.common.utils.UnavailableError: Git is not available in this environment.

This error doesn't occur with 3.15.

![grow-error-317](https://user-images.githubusercontent.com/1012254/33338861-5e52a7ae-d445-11e7-9f0d-e612c39041e9.png)

I tested 3.17 on Mac OSX, and that package seems fine.

**Comment by Zoramite** [comment]
It appears that grow thinks you are on App engine since it can import `google.appengine`. I'll look into it a bit more.
