### ISSUE TITLE
Use styled error pages when using --re-route

### ISSUE THREAD

**Issue by jeremydw** [grow/grow#689]
Currently, when using `--re-route`, we don't show the styled error pages.

- When 404ing, we should display the styled Grow 404 page.
- When encountering a template error, rather than showing the "Internal Server Error" page, we should show the styled error page (with traceback).

**Comment by Zoramite** [comment]
I fixed the issue with the 404 page not showing the styled error page. It was also working for a template error, if you find a specific case of when an exception isn't showing styled let me know.
