### ISSUE TITLE
`--re-route` disables sitemap?

### ISSUE THREAD

**Issue by j9t** [grow/grow#703]
Context: https://groups.google.com/forum/#!topic/growsdk/s-x57uB_DHI.

Pod (spec) example: https://github.com/j9t/hhkaffee.com/blob/master/podspec.yaml.

The pod in question enables sitemap generation. When deploying with the `--re-route` option (see mail thread for context), the sitemap is not generated, in fact deleted. Expected: still generate/keep sitemap.

**Comment by Zoramite** [comment]
This is this todo: https://github.com/grow/grow/blob/0476d894c44c1012433f0355547f31dd37364dea/grow/routing/router.py#L74

I'll work on getting it working for the next release.

**Comment by j9t** [comment]
Thanks.
