### ISSUE TITLE
New grow string formatter escapes HTML entities

### ISSUE THREAD

**Issue by stevenle** [grow/grow#707]
The latest version of grow seems to change the way HTML entities are escaped when used in the `gettext` tag. The older version seemed to mark all strings as `|safe`, so you could do something like:

```
{{_('Hello %(name)s', name='<a href="mailto:alice@example.com">Alice</a>')}}
```

and it would correctly render the link.

Now, let me be clear that IMHO, the HTML entities probably shouldn't actually be rendered unless explicitly marked as `|safe` since any user-generated placeholder values would be a vulnerability, but changing this behavior this way might be more harmful than it is good since it would break a bunch of existing sites. So I think for now, it's better to preserve the previous behavior, and then decide later how to proceed whether we want to continue supporting this behavior or having users explicitly mark their strings as `|safe` moving forward.

**Comment by Zoramite** [comment]
Reverted the change to the gettext in https://github.com/grow/grow/commit/dda8ea39a4f6f43f4c7661fae72205260fb119c5 until the escaping issue can be fixed.

There is some [code in Jinja](https://github.com/pallets/jinja/blob/fe3dadacdf4cf411d0a5b6bbd4d5234697a28af2/jinja2/ext.py#L382-L393) That I believe is handling the case for not worrying about escaping, but for some reason I can't seem to duplicate yet how the built in extension is handling the context functions without the escaping.
