### ISSUE TITLE
So long build process due to recent posts feature

### ISSUE THREAD

**Issue by ViktorZharina** [grow/grow#734]
I use grow for [my blog](http://viktor.zharina.info/en/), recently I have added [feature](https://github.com/ViktorZharina/static-blog-based-on-grow/blob/master/views/notes.html#L19 ) to show recent posts.
My build process takes about 20 minutes (slow). Why it takes so long?  What should I do to build it faster?

**Comment by Zoramite** [comment]
Hi @ViktorZharina 

Sorry to hear about the long build time. I'll test it out a bit and see what is causing it to take so long.

Another thing that you can do to visualize what is going on with grow is to go use [profile.grow.io](https://profile.grow.io) and use the file (`.grow/profile.json`) generated from `grow --profile build` to see what parts are taking up the most time.

Also, is the 20 min build that happens every time you build or just some of the times? I just tested and it seemed to build in about 27 seconds.

**Comment by ViktorZharina** [comment]
Thx for thew answer. Hm, now it takes about 60 seconds and seems like flash in the night.  I will research deeply and write if i will find a way to reproduce long building case.

**Comment by Zoramite** [comment]
I'm going to close this issue for now, let me know if you have troubles in the future.
