### ISSUE TITLE
Can`t  compile new Site

### ISSUE THREAD

**Issue by dev7ch** [grow/grow#750]
```

urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)>

[16485] Failed to execute script grow

```

After trying a loong time to fix it still doenst work, althougfh there is  a lot about this topic around in the web, nothing is fixing your problem.

I simply would like to run `grow init base ./foo`

tryed with pythin 2.7
now python 3.6 is installed link etc ans seems to work correctly

... via hombrew

I am on MacOSX highSierra.

What si going wrong here?

**Comment by dev7ch** [comment]
````

**Comment by Zoramite** [comment]
Duplicate of #601

There are some issues with connecting with github right now since they disabled the [older SSL](https://githubengineering.com/crypto-deprecation-notice/) We are still trying to fix the issue with connecting to Github.
