### ISSUE TITLE
grow install fails due to dependency of keyring

### ISSUE THREAD

**Issue by falkben** [grow/grow#761]
My buildspec.yml file has `pip install grow` and then `grow install`, which used to work, but is now failing, I believe due to a dependency on `keyring` (10.5.0) which in turn has a dependency on `secretstorage`.  It seems that secretstorage removed compatibility with Python 2.7 with their version bump to 3, and keyring doesn't pin the version of secretstorage it requests.

I'm using CodeBuild on AWS to build the grow site, with provided Ubuntu Python 2.7 image.

If grow requirements are updated to a newer version of keyring it might fix this problem, as their setup.py now checks python version to use the correct version of secretstorage (at least with 12.2.0 of keyring).

If there are other suggestions as to how to fix the problem I'm all ears.  Thanks!

**Comment by Zoramite** [comment]
Thanks, I'll test it out with a newer version of keyring and see how it goes.

**Comment by falkben** [comment]
`pip install keyring==12.2.0` first, before `pip install grow` successfully ran my grow commands successfully, for what it's worth.

**Comment by Zoramite** [comment]
I believe that #804 should fix this issue since we aren't using keyring anymore and instead use the file interface for storing oauth authentication information.
