### ISSUE TITLE
Relative path filter assumes slug/index.html paths, doesn't work for slug.html paths?

### ISSUE THREAD

**Issue by vitorio** [grow/grow#789]
Hi!  I need to deploy and alternative version of a site suitable for browsing from a folder on a local disk without a web server, so all the paths need to be relative, and all the filenames need to be explicit (no `./` paths, has to be `./index.html`).

My content paths are all set up as e.g. `/{slug}.html`, not `/{slug}/`; everything is in the root.

When I generate the site, `/content/pages/index.md` has correct relative paths.  However, none of the other content pages do.  When each other content page links to itself, its path is `.`.  When it links to another page, the path is erroneously `../otherpage.html`.

This is tested with the latest grow available through pip, 0.5.1, and adjusting the paths in the codelab scaffold:

 - Changing all the url references in the templates to include the `|relative` filter
 - Changing all the paths in both `_blueprint.yaml`s to e.g. `/posts/{slug}.html`

**Comment by vitorio** [comment]
It appears that the `|relative` filter uses `os.path.relpath`, which apparently expects directories to be passed, not files: https://bugs.python.org/issue18389

Is this intended behavior?  If so, is there an alternative for my use case?

**Comment by vitorio** [comment]
If there isn't a built-in alternative, patching `common/urls.py` `create_relative_path()` according to [this StackOverflow comment](https://stackoverflow.com/questions/17506552/python-os-path-relpath-behavior#comment25450709_17506552) seems to work for my use case, but I don't know if this breaks anything else: `result = os.path.relpath(path, relative_to)` to `result = os.path.relpath(path, os.path.dirname(relative_to))`

**Comment by vitorio** [comment]
Also, it appears there's no way to do a relative URL in Markdown the recommended way.  `[url('/content/pages/archive.md')|relative]` doesn't work, I've had to do `{{g.doc('/content/pages/archive.md').url|relative}}` instead.

**Comment by Zoramite** [comment]
I looked into being able to do a relative filter in the markdown processor, but I don't see a way in markdown extensions to get access to the context to get the url of the current doc to make the path relative to it.
