### ISSUE TITLE
`grow run` does not watch for changes in included files any longer

### ISSUE THREAD

**Issue by pbakaus** [grow/grow#790]
Heya!

I noticed recently that Grow doesn't pick up changes to included files anymore, so if you, like me, inline a CSS file in a partial, like so:

`{% include "/assets/css/main.min.css" %}`

then make changes to that file and reload the page, these changes are not picked up. I have to kill the process and restart, which defeats the purpose of the `grow run` mode. This has worked before – any possibility to bring it back, or any potential workaround?

Thanks!

**Comment by Zoramite** [comment]
I was testing this out a bit with the amp project docs. I wasn't able to get it to not see the changes to the styles. I noticed it took a second or two for the sass to process, but reloading the page picked up the changes for me. Do you have an example of a specific page that I could test it out on?

**Comment by Zoramite** [comment]
One thought on this, the file watching (especially to trigger on included files) uses a dependency graph. If you haven't built the full site, it is possible that the included file isn't showing up in the dependency graph.

**Comment by pbakaus** [comment]
ah interesting (and sorry for the delay in response). I will test this and build the whole site, then try again on my Macbook, to see if it changes anything. Will report back asap.

**Comment by Zoramite** [comment]
If that is the case, than I need to make sure that the dependency graph is being updated correctly with each page load. Because it is supposed to :) It is possible that got messed up and it isn't updating the dependency graph on the dev server.

**Comment by pbakaus** [comment]
Hi again, sorry for the incredible delay!

I confirmed that even with a full build (`grow build`), sass changes are *not* picked up in my local build when in `grow run` mode.

I did the following:

1. `grow run`
2. Open _mission.scss
3. Browse to http://localhost:8080/about/mission/
4. Change line 35 in _mission.scss from `background: white` to `background: red`
5. Observe in terminal that sass task ran successfully and picked up the changes
6. Reload browser window
7. No changes are picked up, even though the generated mission.min.css picked it up, and is imported in the head of the page

Help?

(We confirmed this on several machines)

**Comment by Zoramite** [comment]
My install of the amp docs seems to have issues with the js, probably something with the node version. But I had a thought, you are referencing the minimized css files, but from the static definitions in the podspec they are not fingerprinted... so it could be browser caching that is not looking for the changes.

One thing to try is to turn on [fingerprinting](https://grow.io/docs/podspec/#fingerprints) for the js/css files that you serve. Then the css/js filenames will change each time the minimized file changes.

**Comment by matthiasrohmer** [comment]
Strange thing is it does work in an isolated example pod: [test-grow-cached-includes.zip](https://github.com/grow/grow/files/2505473/test-grow-cached-includes.zip). Just start `grow run` and manually change the classes in `css/styles.css` - they get picked up.

Nevertheless it still breaks for the AMP docs. Maybe it has something to do with gulp not changing the files in a way that identifies them as changed for Grow?

@pbakaus, I know this sucks for the current setup though for the relaunch we are currently using [https://github.com/jungvonmatt/grow-ext-inline-text-assets](https://github.com/jungvonmatt/grow-ext-inline-text-assets) that works around that problem.

**Comment by Zoramite** [comment]
@matthiasrohmer I think that you may have hit this on the head when you talked about gulp not picking up the changes. 

In the later versions of gulp the changes were not updating the `mtime` of the file in the later versions of gulp which was throughing off grow's file watchers. I think that some of the changes that we did should work around the mtime issues completely, but let me know if you are still seeing issues.

See: https://github.com/grow/grow/issues/955
