### ISSUE TITLE
Minimal version of Docker image

### ISSUE THREAD

**Issue by stevenle** [grow/grow#815]
The current version of the ubuntu-based `grow/base` docker image is about 1.13GB.

```
$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
grow/base           latest              bf6ece5cefd5        2 days ago          1.13GB
```

On a cold cache, it can take a while for CI builds to download the image. Might be worth exploring an alpine-based version of grow.

**Comment by Zoramite** [comment]
So I got the base image down to this:

```
REPOSITORY             TAG                 IMAGE ID            CREATED             SIZE
grow/base              latest              238bc6850984        3 hours ago         1.02GB
```

I've added an alpine image. Still need to test it out with a project to make sure that it works correctly, but it comes out to be (uncompressed):

```
REPOSITORY             TAG                 IMAGE ID            CREATED             SIZE
grow/base              alpine-latest       72f1e47de33a        3 hours ago         547MB
```

I was having an issue with the node on the image when I was testing. I'll try and fix that up tomorrow.
