### ISSUE TITLE
/_grow/routes only works on first load

### ISSUE THREAD

**Issue by jeremydw** [grow/grow#855]
The `/_grow/routes` console only works the first time the routing tree is computed. Make a change to the routing by editing the `$path` of a YAML file and the console at `/_grow` fails to load.

**Comment by Zoramite** [comment]
For later fixing: This appears to happen with you change something like the podspec where all of the routes are rebuilt. The `_grow/` routes are added by the local server handler code and it doesn't get redone when the routes are rebuilt.

**Comment by jeremydw** [comment]
Just flagging that I think this is still an issue
