### ISSUE TITLE
Google Docs preprocessor should support folders

### ISSUE THREAD

**Issue by jeremydw** [grow/grow#863]
In addition to specifying a specific ID, you should be able to specify a folder and a collection, and Grow will bind the collection to the documents in the Drive folder. This will be useful for managing collections of pages that all follow the same structure (i.e. Terms of Service or Privacy Policies).

/cc @adelaidemt and @stevenle as an FYI

**Comment by JaredSartin** [comment]
#888 and #889

**Comment by jeremydw** [comment]
Fixed in https://github.com/grow/grow/issues/888
