### ISSUE TITLE
Non-existant doc references do not throw errors.

### ISSUE THREAD

**Issue by pbakaus** [grow/grow#865]
Heya,

this is a pretty strange issue. Here's roughly how to repro:

## 1. How to repro

1. Take a look at [responsive_amp.md](https://github.com/ampproject/docs/blob/master/content/docs/design/responsive_amp.md). specifically this line: `[placeholders & fallbacks]({{g.doc('/content/docs/design/responsive/placeholders.md', locale=doc.locale).url.path}})`
2. Referenced file [placeholders.md](https://github.com/ampproject/docs/blob/master/content/docs/design/responsive_amp/placeholders.md) does not have a special path in the front matter, so inherits the rules from its [_blueprint.yaml](https://github.com/ampproject/docs/blob/master/content/docs/design/responsive_amp/_blueprint.yaml)
3. Actual path thus resolves to `/docs/design/responsive/placeholders.html`

## Actual result

The g.doc function from step 1 returns `/docs/design/placeholders.html`

## Expected result

The g.doc function should return the actual path, `/docs/design/responsive/placeholders.html`.

**Comment by pbakaus** [comment]
...aaaaand nevermind, our bad.. g.doc pointed to `/content/docs/design/responsive/placeholders.md`, which doesn't exist. Would be quite nice if it could throw an error in that case though..

**Comment by Zoramite** [comment]
I think a good fix for this type of thing would be to have it throw an error in the `g.doc` if the doc referenced doesn't exist.

**Comment by pbakaus** [comment]
@Zoramite yep exactly.
