### ISSUE TITLE
Grow 0.6.5 breaks AMP codebase

### ISSUE THREAD

**Issue by pbakaus** [grow/grow#876]
Production build ran fine a few hours ago with Grow 0.6.4, now breaks against Grow 0.6.5, see https://travis-ci.org/ampproject/docs/jobs/476607874 for more details.

**Comment by pbakaus** [comment]
Actual repo to test against: https://github.com/ampproject/docs/tree/master

**Comment by Zoramite** [comment]
Hi @pbakaus one of the changes is to fix #865. From what I can tell of those error most of them seem to be in reference to a nonexistent: `/content/learn/overview.html` does that document exist? or should all those docs be referencing it?

**Comment by pbakaus** [comment]
@Zoramite that file exists, sort of, but it has a `.yaml` extension instead. Grow was previously lenient when it comes to which extension a file had when including it via g.doc. I'm rerunning the build now to see if that was it, thanks!

**Comment by pbakaus** [comment]
I think that was definitely it, but it produces a terrible amount of errors in our code base, probably because a lot of things are in fact broken, so pinning to old version for the current version of the site that we'll replace soon. Thanks for the quick troubleshooting, closing this issue for now!
