### ISSUE TITLE
Checking for document existence

### ISSUE THREAD

**Issue by matthiasrohmer** [grow/grow#877]
Prior to Grow 0.6.5 sometimes in our templates we checked for the existence of a certain document with something along the lines of

```jinja2
{% set collection_index = g.doc('/content/' + collection.collection_path + '/index.md') %}
{% if collection_index.exists %}
```

That now throws an errors before the check even happens. What would be the best way to refactor?  I thought about using `pod.file_exists` but it isn't available in the template.

**Comment by Zoramite** [comment]
A workaround for this would be `{if doc.pod.file_exists('/content/' + collection.collection_path + '/index.md') %}`

Alternatively we could add something like `g.doc_exists`, but I need to think about that more before doing it.

**Comment by matthiasrohmer** [comment]
Hrgz... could have thought two minutes more about it to come up with another way of accessing `pod`. I will check tomorrow if it works and close if it does. Thanks for the quick response!
