### ISSUE TITLE
Build error handling

### ISSUE THREAD

**Issue by stevenle** [grow/grow#904]
When running `grow build`, if any template error occurs, grow continues to try to build the entire site before failing. This can take a lot of time for large sites. Can we stop the builder at the first known build error?

Also, doesn't seem like objectcache is being saved to file when builds err. For sites that use google_cloud_image, that means we need to re-ping the service again for all images.

**Comment by Zoramite** [comment]
You can get faster breakage by running the command without threading. The reason it has to build the entire site is that it doesn't know which sub processes have errored until the end. Alternatively, we could figure out something where an error stops building the other pending docs in the render pool, but it wouldn't stop all of the rendering, just that pool.

I'll see about getting the object caches to save even after errors.
