### ISSUE TITLE
Run certain tagged preprocessors in `grow deploy` and `grow build`

### ISSUE THREAD

**Issue by stevenle** [grow/grow#910]
Related to the build sharding (#908), we may eventually need a way to autorun only certain preprocessors for certain builds/deploys. Can we get something like:

```
grow build --preprocessor-tag=foo
grow deploy --preprocessor-tag=foo
```

**Comment by Zoramite** [comment]
Since you can already run the preprocess command with tags i'm not sure what this adds? If you need to do a specific set of preprocessors in one command you would probably want to make it a `make` command.

Also, if we do want something that controls the preprocessors that run for a deploy I think it would make more sense to have it be part of the podspec deploy config so the build command doesn't need to be modified.

**Comment by jeremydw** [comment]
I think this could also be configured with the deployment target, and use of `autorun@env.<name>` tagging.

**Comment by stevenle** [comment]
Actually you're right, I probably don't need this. My initial use-case was in `fileset` since I use a preprocessor to inject `fileset` as a deployment target. But I just realize I already work around this by having the `fileset` injection happen when grow is loaded, not when the preprocessor is being run.

```python
class FilesetPreprocessor(grow.Preprocessor):
    """Preprocessor for grow that sets up the fileset deploy destination."""

    KIND = 'fileset'

    class Config(messages.Message):
        pass

    def __init__(self, *args, **kwargs):
        super(FilesetPreprocessor, self).__init__(*args, **kwargs)
        if deployments._destination_kinds_to_classes is None:
            deployments.register_builtins()
        if self.KIND not in deployments._destination_kinds_to_classes:
            deployments.register_destination(FilesetDestination)

    def run(self, build=True):
        # Intentionally empty. Since preprocessors are initialized before
        # deployment destinations, we use the preprocessor's constructor to
        # inject a custom destination into grow's list of registered
        # destinations.
        pass
```

Closing this now.
