### ISSUE TITLE
Remove index.html in paths

### ISSUE THREAD

**Issue by matthiasrohmer** [grow/grow#914]
The old routing allowed to set `$path: /docs/` on a document which automatically got resolved to `/docs/index.html` during build time while having the nice `/docs/` path whenever you called `doc.url.path`.

The new routing doesn't allow the unspecific scheme anymore but would give errors during deployment (File is not a directory) if there are documents sharing a sub-path like `/docs/a-document.html`.

It would be nice if the `doc.url.path` property (or another one) would give the path without the `index.html` if it's the last part of the path to have nice URLs without having to manually do something like `{{ doc.url.path.replace('index.html', '') }}` whenever printing a path in the template.

**Comment by Zoramite** [comment]
Do you have an example of this... It should still do the path as `/docs/`.

Usually when you get an error about `file is not a directory` it can be fixed by removing the entire `build/` directory and re-running the build.

**Comment by matthiasrohmer** [comment]
Fixed by #1918.
