### ISSUE TITLE
Built-in Sass preprocessor dies after use in the development server sporadically

### ISSUE THREAD

**Issue by jeremydw** [grow/grow#917]
Traceback:

```
2019-04-09 17:24 grow[10707] (FSEvents.framework) FSEventStreamStop(): failed assertion 'streamRef != NULL'

2019-04-09 17:24 grow[10707] (FSEvents.framework) FSEventStreamInvalidate(): failed assertion 'streamRef != NULL'

2019-04-09 17:24 grow[10707] (FSEvents.framework) FSEventStreamRelease(): failed assertion 'streamRef != NULL'

/var/folders/4z/rq1wgmp90n1_4897k8xlgrnh003jj5/T/_MEIEElyJb/threading.py:1151: RuntimeWarning: tp_compare didn't return -1 or -2 for exception
```

Options:

1. Fix this
1. Remove the built-in Sass preprocessor

**Comment by Zoramite** [comment]
My vote is to remove the built-in preprocessor for sass. If people still want to have a preprocessor for it specifically (as opposed to using gulp or webpack for sass) it could be reworked as an extension.

**Comment by jeremydw** [comment]
All right. Let's get rid of it. I'm supportive.

I'm also supportive of us providing recommended Sass compilation/frontend build setups. Maybe we could settle on a frontend build stack we're happy with and recommend it.

**Comment by Zoramite** [comment]
@jeremydw should we remove the blogger preprocessor at the same time?

**Comment by jeremydw** [comment]
I don't think that needs to be removed now. It's just a Python file whereas
the Sass preprocessor is this whole binding for Libsass (
https://github.com/sass/libsass-python) which would be nice to remove from
Grow core. (Also likely why we're getting this traceback.)
