### ISSUE TITLE
Automatic migration from separate Copy and Translation Google Sheets to a unified one

### ISSUE THREAD

**Issue by jeremydw** [grow/grow#932]
Current situation:
- We have a collection of YAML files formatted for compatibility with `!g.string` tags (and a corresponding Google Sheet with one tab per file).
- We have PO files containing translations (and a corresponding Google Sheet with one tab per locale).

New situation:
- We would like a unified Google Sheet with translations and source copy/strings in the same place.
- Downloading from the Google Sheet fills the `!g.string` YAML files and PO files properly.
- Uploading to the Google Sheet updates the right cells and creates the right sheet structure.

Any thoughts on the correct behavior and structure are welcome.

**Comment by Zoramite** [comment]
Do you have a sample yet of what you want the spreadsheet to look like?
