### ISSUE TITLE
Slugify should escape apostrophes

### ISSUE THREAD

**Issue by stevenle** [grow/grow#939]
Slugify is used in some extensions (like the xml_feed preprocessor) that generate filenames. We should exclude characters like quotes/apostrophes from being included in slugified names.

**Comment by Zoramite** [comment]
I think we made it more lax because of unicode character support. But I wonder if it would be worth it to switch over to something like this slugify library: https://github.com/un33k/python-slugify where it does better unicode support while still stripping out characters.
