### ISSUE TITLE
Installer should suggest adding $HOME/bin to $PATH instead of using alias

### ISSUE THREAD

**Issue by stevenle** [grow/grow#962]
CLIs in general should avoid installation by adding `alias` lines to bash configuration files. I think it's better that grow installs to `$HOME/bin` and suggest adding `export PATH=$PATH:$PATH/bin` to their bashrc (or equivalent).

**Comment by jeremydw** [comment]
Agree, I never really liked the alias approach. This sounds like a good idea to me.
