### ISSUE TITLE
Can't ctrl+c to stop dev server when auto-update message is printed

### ISSUE THREAD

**Issue by stevenle** [grow/grow#963]
When the `Please update to the newest version of the Grow SDK.` message is displayed, `ctrl+c` doesn't work while grow waits for input from the user. Is there a way for it to catch the `ctrl+c` without requiring keyboard input?

**Comment by Zoramite** [comment]
Just to make sure that I understand this... you want to make the keyboard interrupt not kill grow, but just abort out of the update message?

**Comment by stevenle** [comment]
Both :)
