### ISSUE TITLE
pycrypto?

### ISSUE THREAD

**Issue by jirib** [grow/grow#991]
Hi,
pycrypto has latest release in 2014 and I can't even install it via pip on Void Linux as it uses LibreSSL. pycrypto does not exist in OpenBSD as well.

PyCryptodome should be modern alternative - https://www.pycryptodome.org/en/latest/src/introduction.html

**Comment by Zoramite** [comment]
Hi @jirib 

Thanks for bringing it up. I am currently checking in our codebase to see if we are still using pycrypto anywhere. I don't see it being directly used, so either is a sub dependency that we were pinning at a version that we didn't document correctly, or we removed the code that was using it beforehand and just never removed the dependency. I'll try out removing it and make sure that it doesn't break anything.
